package com.eparkingdb.dao.sqlProvider;

import com.common.entity.eparkingCloud.TChargeDetailsReport;
import com.common.entity.eparkingCloud.TChargeDetailsReportCriteria;
import com.common.entity.eparkingCloud.TChargeDetailsReportCriteria.Criteria;
import com.common.entity.eparkingCloud.TChargeDetailsReportCriteria.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class TChargeDetailsReportSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_details_report
     *
     * @mbg.generated
     */
    public String countByExample(TChargeDetailsReportCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_charge_details_report");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_details_report
     *
     * @mbg.generated
     */
    public String deleteByExample(TChargeDetailsReportCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_charge_details_report");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_details_report
     *
     * @mbg.generated
     */
    public String insertSelective(TChargeDetailsReport record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_charge_details_report");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getParkId() != null) {
            sql.VALUES("park_id", "#{parkId,jdbcType=INTEGER}");
        }
        
        if (record.getCompanyId() != null) {
            sql.VALUES("company_id", "#{companyId,jdbcType=INTEGER}");
        }
        
        if (record.getChargeDate() != null) {
            sql.VALUES("charge_date", "#{chargeDate,jdbcType=VARCHAR}");
        }
        
        if (record.getCarNatureDesc() != null) {
            sql.VALUES("car_nature_desc", "#{carNatureDesc,jdbcType=VARCHAR}");
        }
        
        if (record.getChargeAmount() != null) {
            sql.VALUES("charge_amount", "#{chargeAmount,jdbcType=INTEGER}");
        }
        
        if (record.getNeedpayTotal() != null) {
            sql.VALUES("needpay_total", "#{needpayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getActualpayTotal() != null) {
            sql.VALUES("actualpay_total", "#{actualpayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getQpasspayTotal() != null) {
            sql.VALUES("qpasspay_total", "#{qpasspayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getBehalfpayTotal() != null) {
            sql.VALUES("behalfpay_total", "#{behalfpayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getPrepayTotal() != null) {
            sql.VALUES("prepay_total", "#{prepayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getCouponTotal() != null) {
            sql.VALUES("coupon_total", "#{couponTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=VARCHAR}");
        }
        
        if (record.getDutyPerson() != null) {
            sql.VALUES("duty_person", "#{dutyPerson,jdbcType=VARCHAR}");
        }
        
        if (record.getOutPortId() != null) {
            sql.VALUES("out_port_id", "#{outPortId,jdbcType=INTEGER}");
        }
        
        if (record.getWalletpayTotal() != null) {
            sql.VALUES("walletpay_total", "#{walletpayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getInaccesspaidTotal() != null) {
            sql.VALUES("inaccesspaid_total", "#{inaccesspaidTotal,jdbcType=DOUBLE}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_details_report
     *
     * @mbg.generated
     */
    public String selectByExample(TChargeDetailsReportCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("park_id");
        sql.SELECT("company_id");
        sql.SELECT("charge_date");
        sql.SELECT("car_nature_desc");
        sql.SELECT("charge_amount");
        sql.SELECT("needpay_total");
        sql.SELECT("actualpay_total");
        sql.SELECT("qpasspay_total");
        sql.SELECT("behalfpay_total");
        sql.SELECT("prepay_total");
        sql.SELECT("coupon_total");
        sql.SELECT("create_time");
        sql.SELECT("duty_person");
        sql.SELECT("out_port_id");
        sql.SELECT("walletpay_total");
        sql.SELECT("inaccesspaid_total");
        sql.FROM("t_charge_details_report");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_details_report
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TChargeDetailsReport record = (TChargeDetailsReport) parameter.get("record");
        TChargeDetailsReportCriteria example = (TChargeDetailsReportCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("t_charge_details_report");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        }
        
        if (record.getCompanyId() != null) {
            sql.SET("company_id = #{record.companyId,jdbcType=INTEGER}");
        }
        
        if (record.getChargeDate() != null) {
            sql.SET("charge_date = #{record.chargeDate,jdbcType=VARCHAR}");
        }
        
        if (record.getCarNatureDesc() != null) {
            sql.SET("car_nature_desc = #{record.carNatureDesc,jdbcType=VARCHAR}");
        }
        
        if (record.getChargeAmount() != null) {
            sql.SET("charge_amount = #{record.chargeAmount,jdbcType=INTEGER}");
        }
        
        if (record.getNeedpayTotal() != null) {
            sql.SET("needpay_total = #{record.needpayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getActualpayTotal() != null) {
            sql.SET("actualpay_total = #{record.actualpayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getQpasspayTotal() != null) {
            sql.SET("qpasspay_total = #{record.qpasspayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getBehalfpayTotal() != null) {
            sql.SET("behalfpay_total = #{record.behalfpayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getPrepayTotal() != null) {
            sql.SET("prepay_total = #{record.prepayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getCouponTotal() != null) {
            sql.SET("coupon_total = #{record.couponTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=VARCHAR}");
        }
        
        if (record.getDutyPerson() != null) {
            sql.SET("duty_person = #{record.dutyPerson,jdbcType=VARCHAR}");
        }
        
        if (record.getOutPortId() != null) {
            sql.SET("out_port_id = #{record.outPortId,jdbcType=INTEGER}");
        }
        
        if (record.getWalletpayTotal() != null) {
            sql.SET("walletpay_total = #{record.walletpayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getInaccesspaidTotal() != null) {
            sql.SET("inaccesspaid_total = #{record.inaccesspaidTotal,jdbcType=DOUBLE}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_details_report
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_charge_details_report");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        sql.SET("company_id = #{record.companyId,jdbcType=INTEGER}");
        sql.SET("charge_date = #{record.chargeDate,jdbcType=VARCHAR}");
        sql.SET("car_nature_desc = #{record.carNatureDesc,jdbcType=VARCHAR}");
        sql.SET("charge_amount = #{record.chargeAmount,jdbcType=INTEGER}");
        sql.SET("needpay_total = #{record.needpayTotal,jdbcType=DOUBLE}");
        sql.SET("actualpay_total = #{record.actualpayTotal,jdbcType=DOUBLE}");
        sql.SET("qpasspay_total = #{record.qpasspayTotal,jdbcType=DOUBLE}");
        sql.SET("behalfpay_total = #{record.behalfpayTotal,jdbcType=DOUBLE}");
        sql.SET("prepay_total = #{record.prepayTotal,jdbcType=DOUBLE}");
        sql.SET("coupon_total = #{record.couponTotal,jdbcType=DOUBLE}");
        sql.SET("create_time = #{record.createTime,jdbcType=VARCHAR}");
        sql.SET("duty_person = #{record.dutyPerson,jdbcType=VARCHAR}");
        sql.SET("out_port_id = #{record.outPortId,jdbcType=INTEGER}");
        sql.SET("walletpay_total = #{record.walletpayTotal,jdbcType=DOUBLE}");
        sql.SET("inaccesspaid_total = #{record.inaccesspaidTotal,jdbcType=DOUBLE}");
        
        TChargeDetailsReportCriteria example = (TChargeDetailsReportCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_details_report
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TChargeDetailsReport record) {
        SQL sql = new SQL();
        sql.UPDATE("t_charge_details_report");
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{parkId,jdbcType=INTEGER}");
        }
        
        if (record.getCompanyId() != null) {
            sql.SET("company_id = #{companyId,jdbcType=INTEGER}");
        }
        
        if (record.getChargeDate() != null) {
            sql.SET("charge_date = #{chargeDate,jdbcType=VARCHAR}");
        }
        
        if (record.getCarNatureDesc() != null) {
            sql.SET("car_nature_desc = #{carNatureDesc,jdbcType=VARCHAR}");
        }
        
        if (record.getChargeAmount() != null) {
            sql.SET("charge_amount = #{chargeAmount,jdbcType=INTEGER}");
        }
        
        if (record.getNeedpayTotal() != null) {
            sql.SET("needpay_total = #{needpayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getActualpayTotal() != null) {
            sql.SET("actualpay_total = #{actualpayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getQpasspayTotal() != null) {
            sql.SET("qpasspay_total = #{qpasspayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getBehalfpayTotal() != null) {
            sql.SET("behalfpay_total = #{behalfpayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getPrepayTotal() != null) {
            sql.SET("prepay_total = #{prepayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getCouponTotal() != null) {
            sql.SET("coupon_total = #{couponTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=VARCHAR}");
        }
        
        if (record.getDutyPerson() != null) {
            sql.SET("duty_person = #{dutyPerson,jdbcType=VARCHAR}");
        }
        
        if (record.getOutPortId() != null) {
            sql.SET("out_port_id = #{outPortId,jdbcType=INTEGER}");
        }
        
        if (record.getWalletpayTotal() != null) {
            sql.SET("walletpay_total = #{walletpayTotal,jdbcType=DOUBLE}");
        }
        
        if (record.getInaccesspaidTotal() != null) {
            sql.SET("inaccesspaid_total = #{inaccesspaidTotal,jdbcType=DOUBLE}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_details_report
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TChargeDetailsReportCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}