package com.eparkingdb.dao.sqlProvider;

import com.common.entity.eparkingCloud.TPaymentDetails;
import com.common.entity.eparkingCloud.TPaymentDetailsCriteria;
import com.common.entity.eparkingCloud.TPaymentDetailsCriteria.Criteria;
import com.common.entity.eparkingCloud.TPaymentDetailsCriteria.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class TPaymentDetailsSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    public String countByExample(TPaymentDetailsCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_payment_details");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    public String deleteByExample(TPaymentDetailsCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_payment_details");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    public String insertSelective(TPaymentDetails record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_payment_details");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getCarPlate() != null) {
            sql.VALUES("car_plate", "#{carPlate,jdbcType=VARCHAR}");
        }
        
        if (record.getParkId() != null) {
            sql.VALUES("park_id", "#{parkId,jdbcType=INTEGER}");
        }
        
        if (record.getOrderId() != null) {
            sql.VALUES("order_id", "#{orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getPaymentMethod() != null) {
            sql.VALUES("payment_method", "#{paymentMethod,jdbcType=INTEGER}");
        }
        
        if (record.getAcquiringChannel() != null) {
            sql.VALUES("acquiring_channel", "#{acquiringChannel,jdbcType=INTEGER}");
        }
        
        if (record.getPaymentChannel() != null) {
            sql.VALUES("payment_channel", "#{paymentChannel,jdbcType=INTEGER}");
        }
        
        if (record.getPaymentOrderId() != null) {
            sql.VALUES("payment_order_id", "#{paymentOrderId,jdbcType=VARCHAR}");
        }
        
        if (record.getInTime() != null) {
            sql.VALUES("in_time", "#{inTime,jdbcType=VARCHAR}");
        }
        
        if (record.getOutTime() != null) {
            sql.VALUES("out_time", "#{outTime,jdbcType=VARCHAR}");
        }
        
        if (record.getAmount() != null) {
            sql.VALUES("amount", "#{amount,jdbcType=DOUBLE}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    public String selectByExample(TPaymentDetailsCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("car_plate");
        sql.SELECT("park_id");
        sql.SELECT("order_id");
        sql.SELECT("payment_method");
        sql.SELECT("acquiring_channel");
        sql.SELECT("payment_channel");
        sql.SELECT("payment_order_id");
        sql.SELECT("in_time");
        sql.SELECT("out_time");
        sql.SELECT("amount");
        sql.FROM("t_payment_details");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        TPaymentDetails record = (TPaymentDetails) parameter.get("record");
        TPaymentDetailsCriteria example = (TPaymentDetailsCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("t_payment_details");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getCarPlate() != null) {
            sql.SET("car_plate = #{record.carPlate,jdbcType=VARCHAR}");
        }
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        }
        
        if (record.getOrderId() != null) {
            sql.SET("order_id = #{record.orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getPaymentMethod() != null) {
            sql.SET("payment_method = #{record.paymentMethod,jdbcType=INTEGER}");
        }
        
        if (record.getAcquiringChannel() != null) {
            sql.SET("acquiring_channel = #{record.acquiringChannel,jdbcType=INTEGER}");
        }
        
        if (record.getPaymentChannel() != null) {
            sql.SET("payment_channel = #{record.paymentChannel,jdbcType=INTEGER}");
        }
        
        if (record.getPaymentOrderId() != null) {
            sql.SET("payment_order_id = #{record.paymentOrderId,jdbcType=VARCHAR}");
        }
        
        if (record.getInTime() != null) {
            sql.SET("in_time = #{record.inTime,jdbcType=VARCHAR}");
        }
        
        if (record.getOutTime() != null) {
            sql.SET("out_time = #{record.outTime,jdbcType=VARCHAR}");
        }
        
        if (record.getAmount() != null) {
            sql.SET("amount = #{record.amount,jdbcType=DOUBLE}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_payment_details");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("car_plate = #{record.carPlate,jdbcType=VARCHAR}");
        sql.SET("park_id = #{record.parkId,jdbcType=INTEGER}");
        sql.SET("order_id = #{record.orderId,jdbcType=VARCHAR}");
        sql.SET("payment_method = #{record.paymentMethod,jdbcType=INTEGER}");
        sql.SET("acquiring_channel = #{record.acquiringChannel,jdbcType=INTEGER}");
        sql.SET("payment_channel = #{record.paymentChannel,jdbcType=INTEGER}");
        sql.SET("payment_order_id = #{record.paymentOrderId,jdbcType=VARCHAR}");
        sql.SET("in_time = #{record.inTime,jdbcType=VARCHAR}");
        sql.SET("out_time = #{record.outTime,jdbcType=VARCHAR}");
        sql.SET("amount = #{record.amount,jdbcType=DOUBLE}");
        
        TPaymentDetailsCriteria example = (TPaymentDetailsCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(TPaymentDetails record) {
        SQL sql = new SQL();
        sql.UPDATE("t_payment_details");
        
        if (record.getCarPlate() != null) {
            sql.SET("car_plate = #{carPlate,jdbcType=VARCHAR}");
        }
        
        if (record.getParkId() != null) {
            sql.SET("park_id = #{parkId,jdbcType=INTEGER}");
        }
        
        if (record.getOrderId() != null) {
            sql.SET("order_id = #{orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getPaymentMethod() != null) {
            sql.SET("payment_method = #{paymentMethod,jdbcType=INTEGER}");
        }
        
        if (record.getAcquiringChannel() != null) {
            sql.SET("acquiring_channel = #{acquiringChannel,jdbcType=INTEGER}");
        }
        
        if (record.getPaymentChannel() != null) {
            sql.SET("payment_channel = #{paymentChannel,jdbcType=INTEGER}");
        }
        
        if (record.getPaymentOrderId() != null) {
            sql.SET("payment_order_id = #{paymentOrderId,jdbcType=VARCHAR}");
        }
        
        if (record.getInTime() != null) {
            sql.SET("in_time = #{inTime,jdbcType=VARCHAR}");
        }
        
        if (record.getOutTime() != null) {
            sql.SET("out_time = #{outTime,jdbcType=VARCHAR}");
        }
        
        if (record.getAmount() != null) {
            sql.SET("amount = #{amount,jdbcType=DOUBLE}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, TPaymentDetailsCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}