package com.eparkingdb.dao;

import com.common.entity.eparkingCloud.TCarWalletReport;
import com.common.entity.eparkingCloud.TCarWalletReportCriteria;
import com.eparkingdb.dao.sqlProvider.TCarWalletReportSqlProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TCarWalletReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_wallet_report
     *
     * @mbg.generated
     */
    @SelectProvider(type= TCarWalletReportSqlProvider.class, method="countByExample")
    long countByExample(TCarWalletReportCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_wallet_report
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TCarWalletReportSqlProvider.class, method="deleteByExample")
    int deleteByExample(TCarWalletReportCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_wallet_report
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_car_wallet_report",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_wallet_report
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_car_wallet_report (id, company_id, ",
        "park_id, statistics_time, ",
        "need_pay, actual_pay, ",
        "use_pay, total_wallet_banance, ",
        "create_time)",
        "values (#{id,jdbcType=INTEGER}, #{companyId,jdbcType=INTEGER}, ",
        "#{parkId,jdbcType=INTEGER}, #{statisticsTime,jdbcType=VARCHAR}, ",
        "#{needPay,jdbcType=DOUBLE}, #{actualPay,jdbcType=DOUBLE}, ",
        "#{usePay,jdbcType=DOUBLE}, #{totalWalletBanance,jdbcType=DOUBLE}, ",
        "#{createTime,jdbcType=VARCHAR})"
    })
    int insert(TCarWalletReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_wallet_report
     *
     * @mbg.generated
     */
    @InsertProvider(type=TCarWalletReportSqlProvider.class, method="insertSelective")
    int insertSelective(TCarWalletReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_wallet_report
     *
     * @mbg.generated
     */
    @SelectProvider(type=TCarWalletReportSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType= JdbcType.INTEGER, id=true),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="statistics_time", property="statisticsTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="need_pay", property="needPay", jdbcType=JdbcType.DOUBLE),
        @Result(column="actual_pay", property="actualPay", jdbcType=JdbcType.DOUBLE),
        @Result(column="use_pay", property="usePay", jdbcType=JdbcType.DOUBLE),
        @Result(column="total_wallet_banance", property="totalWalletBanance", jdbcType=JdbcType.DOUBLE),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR)
    })
    List<TCarWalletReport> selectByExample(TCarWalletReportCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_wallet_report
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, company_id, park_id, statistics_time, need_pay, actual_pay, use_pay, total_wallet_banance, ",
        "create_time",
        "from t_car_wallet_report",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="statistics_time", property="statisticsTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="need_pay", property="needPay", jdbcType=JdbcType.DOUBLE),
        @Result(column="actual_pay", property="actualPay", jdbcType=JdbcType.DOUBLE),
        @Result(column="use_pay", property="usePay", jdbcType=JdbcType.DOUBLE),
        @Result(column="total_wallet_banance", property="totalWalletBanance", jdbcType=JdbcType.DOUBLE),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR)
    })
    TCarWalletReport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_wallet_report
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TCarWalletReportSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TCarWalletReport record, @Param("example") TCarWalletReportCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_wallet_report
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TCarWalletReportSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TCarWalletReport record, @Param("example") TCarWalletReportCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_wallet_report
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TCarWalletReportSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TCarWalletReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_car_wallet_report
     *
     * @mbg.generated
     */
    @Update({
        "update t_car_wallet_report",
        "set company_id = #{companyId,jdbcType=INTEGER},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "statistics_time = #{statisticsTime,jdbcType=VARCHAR},",
          "need_pay = #{needPay,jdbcType=DOUBLE},",
          "actual_pay = #{actualPay,jdbcType=DOUBLE},",
          "use_pay = #{usePay,jdbcType=DOUBLE},",
          "total_wallet_banance = #{totalWalletBanance,jdbcType=DOUBLE},",
          "create_time = #{createTime,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TCarWalletReport record);
}