package com.eparkingdb.dao;

import com.common.entity.eparkingCloud.TChargeRule;
import com.common.entity.eparkingCloud.TChargeRuleCriteria;
import com.eparkingdb.dao.sqlProvider.TChargeRuleSqlProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TChargeRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    @SelectProvider(type= TChargeRuleSqlProvider.class, method="countByExample")
    long countByExample(TChargeRuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TChargeRuleSqlProvider.class, method="deleteByExample")
    int deleteByExample(TChargeRuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_charge_rule",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_charge_rule (id, park_id, ",
        "is_Holiday_Use, timesec_start, ",
        "timesec_end, car_type_id, ",
        "free_time, free_time_fee, ",
        "base_time1, base_time1_fee, ",
        "base_time2, base_time2_fee, ",
        "unit_time, unit_time_fee, ",
        "h24_unit_time, h24_unit_time_fee, ",
        "surpass_time, max_day1_fee, ",
        "max_dayn_fee, h24_rule, ",
        "max_sectime_fee, is_max_sectime_fee_by_add, ",
        "is_max_24_fee_by_add, free0_time, ",
        "free0_time_fee, base_time3, ",
        "base_time3_fee, base_time4, ",
        "base_time4_fee, unit1_sectime, ",
        "unit1_time, unit1_time_fee, ",
        "unit1_maxfee, unit2_sectime, ",
        "unit2_time, unit2_time_fee, ",
        "unit2_maxfee, unit3_sectime, ",
        "unit3_time, unit3_time_fee, ",
        "unit3_maxfee, h24_cal_mode)",
        "values (#{id,jdbcType=INTEGER}, #{parkId,jdbcType=INTEGER}, ",
        "#{isHolidayUse,jdbcType=INTEGER}, #{timesecStart,jdbcType=VARCHAR}, ",
        "#{timesecEnd,jdbcType=VARCHAR}, #{carTypeId,jdbcType=INTEGER}, ",
        "#{freeTime,jdbcType=INTEGER}, #{freeTimeFee,jdbcType=DOUBLE}, ",
        "#{baseTime1,jdbcType=INTEGER}, #{baseTime1Fee,jdbcType=DOUBLE}, ",
        "#{baseTime2,jdbcType=INTEGER}, #{baseTime2Fee,jdbcType=DOUBLE}, ",
        "#{unitTime,jdbcType=INTEGER}, #{unitTimeFee,jdbcType=DOUBLE}, ",
        "#{h24UnitTime,jdbcType=INTEGER}, #{h24UnitTimeFee,jdbcType=DOUBLE}, ",
        "#{surpassTime,jdbcType=INTEGER}, #{maxDay1Fee,jdbcType=DOUBLE}, ",
        "#{maxDaynFee,jdbcType=DOUBLE}, #{h24Rule,jdbcType=INTEGER}, ",
        "#{maxSectimeFee,jdbcType=DOUBLE}, #{isMaxSectimeFeeByAdd,jdbcType=INTEGER}, ",
        "#{isMax24FeeByAdd,jdbcType=INTEGER}, #{free0Time,jdbcType=INTEGER}, ",
        "#{free0TimeFee,jdbcType=DOUBLE}, #{baseTime3,jdbcType=INTEGER}, ",
        "#{baseTime3Fee,jdbcType=DOUBLE}, #{baseTime4,jdbcType=INTEGER}, ",
        "#{baseTime4Fee,jdbcType=DOUBLE}, #{unit1Sectime,jdbcType=INTEGER}, ",
        "#{unit1Time,jdbcType=INTEGER}, #{unit1TimeFee,jdbcType=DOUBLE}, ",
        "#{unit1Maxfee,jdbcType=DOUBLE}, #{unit2Sectime,jdbcType=INTEGER}, ",
        "#{unit2Time,jdbcType=INTEGER}, #{unit2TimeFee,jdbcType=DOUBLE}, ",
        "#{unit2Maxfee,jdbcType=DOUBLE}, #{unit3Sectime,jdbcType=INTEGER}, ",
        "#{unit3Time,jdbcType=INTEGER}, #{unit3TimeFee,jdbcType=DOUBLE}, ",
        "#{unit3Maxfee,jdbcType=DOUBLE}, #{h24CalMode,jdbcType=INTEGER})"
    })
    int insert(TChargeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    @InsertProvider(type=TChargeRuleSqlProvider.class, method="insertSelective")
    int insertSelective(TChargeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    @SelectProvider(type=TChargeRuleSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="is_Holiday_Use", property="isHolidayUse", jdbcType=JdbcType.INTEGER),
        @Result(column="timesec_start", property="timesecStart", jdbcType=JdbcType.VARCHAR),
        @Result(column="timesec_end", property="timesecEnd", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_type_id", property="carTypeId", jdbcType=JdbcType.INTEGER),
        @Result(column="free_time", property="freeTime", jdbcType=JdbcType.INTEGER),
        @Result(column="free_time_fee", property="freeTimeFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="base_time1", property="baseTime1", jdbcType=JdbcType.INTEGER),
        @Result(column="base_time1_fee", property="baseTime1Fee", jdbcType=JdbcType.DOUBLE),
        @Result(column="base_time2", property="baseTime2", jdbcType=JdbcType.INTEGER),
        @Result(column="base_time2_fee", property="baseTime2Fee", jdbcType=JdbcType.DOUBLE),
        @Result(column="unit_time", property="unitTime", jdbcType=JdbcType.INTEGER),
        @Result(column="unit_time_fee", property="unitTimeFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="h24_unit_time", property="h24UnitTime", jdbcType=JdbcType.INTEGER),
        @Result(column="h24_unit_time_fee", property="h24UnitTimeFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="surpass_time", property="surpassTime", jdbcType=JdbcType.INTEGER),
        @Result(column="max_day1_fee", property="maxDay1Fee", jdbcType=JdbcType.DOUBLE),
        @Result(column="max_dayn_fee", property="maxDaynFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="h24_rule", property="h24Rule", jdbcType=JdbcType.INTEGER),
        @Result(column="max_sectime_fee", property="maxSectimeFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="is_max_sectime_fee_by_add", property="isMaxSectimeFeeByAdd", jdbcType=JdbcType.INTEGER),
        @Result(column="is_max_24_fee_by_add", property="isMax24FeeByAdd", jdbcType=JdbcType.INTEGER),
        @Result(column="free0_time", property="free0Time", jdbcType=JdbcType.INTEGER),
        @Result(column="free0_time_fee", property="free0TimeFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="base_time3", property="baseTime3", jdbcType=JdbcType.INTEGER),
        @Result(column="base_time3_fee", property="baseTime3Fee", jdbcType=JdbcType.DOUBLE),
        @Result(column="base_time4", property="baseTime4", jdbcType=JdbcType.INTEGER),
        @Result(column="base_time4_fee", property="baseTime4Fee", jdbcType=JdbcType.DOUBLE),
        @Result(column="unit1_sectime", property="unit1Sectime", jdbcType=JdbcType.INTEGER),
        @Result(column="unit1_time", property="unit1Time", jdbcType=JdbcType.INTEGER),
        @Result(column="unit1_time_fee", property="unit1TimeFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="unit1_maxfee", property="unit1Maxfee", jdbcType=JdbcType.DOUBLE),
        @Result(column="unit2_sectime", property="unit2Sectime", jdbcType=JdbcType.INTEGER),
        @Result(column="unit2_time", property="unit2Time", jdbcType=JdbcType.INTEGER),
        @Result(column="unit2_time_fee", property="unit2TimeFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="unit2_maxfee", property="unit2Maxfee", jdbcType=JdbcType.DOUBLE),
        @Result(column="unit3_sectime", property="unit3Sectime", jdbcType=JdbcType.INTEGER),
        @Result(column="unit3_time", property="unit3Time", jdbcType=JdbcType.INTEGER),
        @Result(column="unit3_time_fee", property="unit3TimeFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="unit3_maxfee", property="unit3Maxfee", jdbcType=JdbcType.DOUBLE),
        @Result(column="h24_cal_mode", property="h24CalMode", jdbcType=JdbcType.INTEGER)
    })
    List<TChargeRule> selectByExample(TChargeRuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, park_id, is_Holiday_Use, timesec_start, timesec_end, car_type_id, free_time, ",
        "free_time_fee, base_time1, base_time1_fee, base_time2, base_time2_fee, unit_time, ",
        "unit_time_fee, h24_unit_time, h24_unit_time_fee, surpass_time, max_day1_fee, ",
        "max_dayn_fee, h24_rule, max_sectime_fee, is_max_sectime_fee_by_add, is_max_24_fee_by_add, ",
        "free0_time, free0_time_fee, base_time3, base_time3_fee, base_time4, base_time4_fee, ",
        "unit1_sectime, unit1_time, unit1_time_fee, unit1_maxfee, unit2_sectime, unit2_time, ",
        "unit2_time_fee, unit2_maxfee, unit3_sectime, unit3_time, unit3_time_fee, unit3_maxfee, ",
        "h24_cal_mode",
        "from t_charge_rule",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="is_Holiday_Use", property="isHolidayUse", jdbcType=JdbcType.INTEGER),
        @Result(column="timesec_start", property="timesecStart", jdbcType=JdbcType.VARCHAR),
        @Result(column="timesec_end", property="timesecEnd", jdbcType=JdbcType.VARCHAR),
        @Result(column="car_type_id", property="carTypeId", jdbcType=JdbcType.INTEGER),
        @Result(column="free_time", property="freeTime", jdbcType=JdbcType.INTEGER),
        @Result(column="free_time_fee", property="freeTimeFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="base_time1", property="baseTime1", jdbcType=JdbcType.INTEGER),
        @Result(column="base_time1_fee", property="baseTime1Fee", jdbcType=JdbcType.DOUBLE),
        @Result(column="base_time2", property="baseTime2", jdbcType=JdbcType.INTEGER),
        @Result(column="base_time2_fee", property="baseTime2Fee", jdbcType=JdbcType.DOUBLE),
        @Result(column="unit_time", property="unitTime", jdbcType=JdbcType.INTEGER),
        @Result(column="unit_time_fee", property="unitTimeFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="h24_unit_time", property="h24UnitTime", jdbcType=JdbcType.INTEGER),
        @Result(column="h24_unit_time_fee", property="h24UnitTimeFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="surpass_time", property="surpassTime", jdbcType=JdbcType.INTEGER),
        @Result(column="max_day1_fee", property="maxDay1Fee", jdbcType=JdbcType.DOUBLE),
        @Result(column="max_dayn_fee", property="maxDaynFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="h24_rule", property="h24Rule", jdbcType=JdbcType.INTEGER),
        @Result(column="max_sectime_fee", property="maxSectimeFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="is_max_sectime_fee_by_add", property="isMaxSectimeFeeByAdd", jdbcType=JdbcType.INTEGER),
        @Result(column="is_max_24_fee_by_add", property="isMax24FeeByAdd", jdbcType=JdbcType.INTEGER),
        @Result(column="free0_time", property="free0Time", jdbcType=JdbcType.INTEGER),
        @Result(column="free0_time_fee", property="free0TimeFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="base_time3", property="baseTime3", jdbcType=JdbcType.INTEGER),
        @Result(column="base_time3_fee", property="baseTime3Fee", jdbcType=JdbcType.DOUBLE),
        @Result(column="base_time4", property="baseTime4", jdbcType=JdbcType.INTEGER),
        @Result(column="base_time4_fee", property="baseTime4Fee", jdbcType=JdbcType.DOUBLE),
        @Result(column="unit1_sectime", property="unit1Sectime", jdbcType=JdbcType.INTEGER),
        @Result(column="unit1_time", property="unit1Time", jdbcType=JdbcType.INTEGER),
        @Result(column="unit1_time_fee", property="unit1TimeFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="unit1_maxfee", property="unit1Maxfee", jdbcType=JdbcType.DOUBLE),
        @Result(column="unit2_sectime", property="unit2Sectime", jdbcType=JdbcType.INTEGER),
        @Result(column="unit2_time", property="unit2Time", jdbcType=JdbcType.INTEGER),
        @Result(column="unit2_time_fee", property="unit2TimeFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="unit2_maxfee", property="unit2Maxfee", jdbcType=JdbcType.DOUBLE),
        @Result(column="unit3_sectime", property="unit3Sectime", jdbcType=JdbcType.INTEGER),
        @Result(column="unit3_time", property="unit3Time", jdbcType=JdbcType.INTEGER),
        @Result(column="unit3_time_fee", property="unit3TimeFee", jdbcType=JdbcType.DOUBLE),
        @Result(column="unit3_maxfee", property="unit3Maxfee", jdbcType=JdbcType.DOUBLE),
        @Result(column="h24_cal_mode", property="h24CalMode", jdbcType=JdbcType.INTEGER)
    })
    TChargeRule selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TChargeRuleSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TChargeRule record, @Param("example") TChargeRuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TChargeRuleSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TChargeRule record, @Param("example") TChargeRuleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TChargeRuleSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TChargeRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_charge_rule
     *
     * @mbg.generated
     */
    @Update({
        "update t_charge_rule",
        "set park_id = #{parkId,jdbcType=INTEGER},",
          "is_Holiday_Use = #{isHolidayUse,jdbcType=INTEGER},",
          "timesec_start = #{timesecStart,jdbcType=VARCHAR},",
          "timesec_end = #{timesecEnd,jdbcType=VARCHAR},",
          "car_type_id = #{carTypeId,jdbcType=INTEGER},",
          "free_time = #{freeTime,jdbcType=INTEGER},",
          "free_time_fee = #{freeTimeFee,jdbcType=DOUBLE},",
          "base_time1 = #{baseTime1,jdbcType=INTEGER},",
          "base_time1_fee = #{baseTime1Fee,jdbcType=DOUBLE},",
          "base_time2 = #{baseTime2,jdbcType=INTEGER},",
          "base_time2_fee = #{baseTime2Fee,jdbcType=DOUBLE},",
          "unit_time = #{unitTime,jdbcType=INTEGER},",
          "unit_time_fee = #{unitTimeFee,jdbcType=DOUBLE},",
          "h24_unit_time = #{h24UnitTime,jdbcType=INTEGER},",
          "h24_unit_time_fee = #{h24UnitTimeFee,jdbcType=DOUBLE},",
          "surpass_time = #{surpassTime,jdbcType=INTEGER},",
          "max_day1_fee = #{maxDay1Fee,jdbcType=DOUBLE},",
          "max_dayn_fee = #{maxDaynFee,jdbcType=DOUBLE},",
          "h24_rule = #{h24Rule,jdbcType=INTEGER},",
          "max_sectime_fee = #{maxSectimeFee,jdbcType=DOUBLE},",
          "is_max_sectime_fee_by_add = #{isMaxSectimeFeeByAdd,jdbcType=INTEGER},",
          "is_max_24_fee_by_add = #{isMax24FeeByAdd,jdbcType=INTEGER},",
          "free0_time = #{free0Time,jdbcType=INTEGER},",
          "free0_time_fee = #{free0TimeFee,jdbcType=DOUBLE},",
          "base_time3 = #{baseTime3,jdbcType=INTEGER},",
          "base_time3_fee = #{baseTime3Fee,jdbcType=DOUBLE},",
          "base_time4 = #{baseTime4,jdbcType=INTEGER},",
          "base_time4_fee = #{baseTime4Fee,jdbcType=DOUBLE},",
          "unit1_sectime = #{unit1Sectime,jdbcType=INTEGER},",
          "unit1_time = #{unit1Time,jdbcType=INTEGER},",
          "unit1_time_fee = #{unit1TimeFee,jdbcType=DOUBLE},",
          "unit1_maxfee = #{unit1Maxfee,jdbcType=DOUBLE},",
          "unit2_sectime = #{unit2Sectime,jdbcType=INTEGER},",
          "unit2_time = #{unit2Time,jdbcType=INTEGER},",
          "unit2_time_fee = #{unit2TimeFee,jdbcType=DOUBLE},",
          "unit2_maxfee = #{unit2Maxfee,jdbcType=DOUBLE},",
          "unit3_sectime = #{unit3Sectime,jdbcType=INTEGER},",
          "unit3_time = #{unit3Time,jdbcType=INTEGER},",
          "unit3_time_fee = #{unit3TimeFee,jdbcType=DOUBLE},",
          "unit3_maxfee = #{unit3Maxfee,jdbcType=DOUBLE},",
          "h24_cal_mode = #{h24CalMode,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TChargeRule record);
}