package com.eparkingdb.dao;

import com.common.entity.eparkingCloud.TCompanyNotice;
import com.common.entity.eparkingCloud.TCompanyNoticeCriteria;
import com.eparkingdb.dao.sqlProvider.TCompanyNoticeSqlProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TCompanyNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_notice
     *
     * @mbg.generated
     */
    @SelectProvider(type= TCompanyNoticeSqlProvider.class, method="countByExample")
    long countByExample(TCompanyNoticeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_notice
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TCompanyNoticeSqlProvider.class, method="deleteByExample")
    int deleteByExample(TCompanyNoticeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_notice
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_company_notice",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_notice
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_company_notice (id, company_id, ",
        "park_id, member_id, ",
        "title, content, ",
        "update_time, create_time, ",
        "user_id)",
        "values (#{id,jdbcType=INTEGER}, #{companyId,jdbcType=INTEGER}, ",
        "#{parkId,jdbcType=INTEGER}, #{memberId,jdbcType=VARCHAR}, ",
        "#{title,jdbcType=VARCHAR}, #{content,jdbcType=VARCHAR}, ",
        "#{updateTime,jdbcType=VARCHAR}, #{createTime,jdbcType=VARCHAR}, ",
        "#{userId,jdbcType=INTEGER})"
    })
    int insert(TCompanyNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_notice
     *
     * @mbg.generated
     */
    @InsertProvider(type=TCompanyNoticeSqlProvider.class, method="insertSelective")
    int insertSelective(TCompanyNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_notice
     *
     * @mbg.generated
     */
    @SelectProvider(type=TCompanyNoticeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType= JdbcType.INTEGER, id=true),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.VARCHAR),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER)
    })
    List<TCompanyNotice> selectByExample(TCompanyNoticeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_notice
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, company_id, park_id, member_id, title, content, update_time, create_time, ",
        "user_id",
        "from t_company_notice",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="company_id", property="companyId", jdbcType=JdbcType.INTEGER),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="member_id", property="memberId", jdbcType=JdbcType.VARCHAR),
        @Result(column="title", property="title", jdbcType=JdbcType.VARCHAR),
        @Result(column="content", property="content", jdbcType=JdbcType.VARCHAR),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER)
    })
    TCompanyNotice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_notice
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TCompanyNoticeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TCompanyNotice record, @Param("example") TCompanyNoticeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_notice
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TCompanyNoticeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TCompanyNotice record, @Param("example") TCompanyNoticeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_notice
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TCompanyNoticeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TCompanyNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_company_notice
     *
     * @mbg.generated
     */
    @Update({
        "update t_company_notice",
        "set company_id = #{companyId,jdbcType=INTEGER},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "member_id = #{memberId,jdbcType=VARCHAR},",
          "title = #{title,jdbcType=VARCHAR},",
          "content = #{content,jdbcType=VARCHAR},",
          "update_time = #{updateTime,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=VARCHAR},",
          "user_id = #{userId,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TCompanyNotice record);
}