package com.eparkingdb.dao;

import com.common.entity.eparkingCloud.TPaymentDetails;
import com.common.entity.eparkingCloud.TPaymentDetailsCriteria;
import com.eparkingdb.dao.sqlProvider.TPaymentDetailsSqlProvider;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface TPaymentDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    @SelectProvider(type= TPaymentDetailsSqlProvider.class, method="countByExample")
    long countByExample(TPaymentDetailsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TPaymentDetailsSqlProvider.class, method="deleteByExample")
    int deleteByExample(TPaymentDetailsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    @Delete({
        "delete from t_payment_details",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_payment_details (id, car_plate, ",
        "park_id, order_id, ",
        "payment_method, acquiring_channel, ",
        "payment_channel, payment_order_id, ",
        "in_time, out_time, ",
        "amount)",
        "values (#{id,jdbcType=INTEGER}, #{carPlate,jdbcType=VARCHAR}, ",
        "#{parkId,jdbcType=INTEGER}, #{orderId,jdbcType=VARCHAR}, ",
        "#{paymentMethod,jdbcType=INTEGER}, #{acquiringChannel,jdbcType=INTEGER}, ",
        "#{paymentChannel,jdbcType=INTEGER}, #{paymentOrderId,jdbcType=VARCHAR}, ",
        "#{inTime,jdbcType=VARCHAR}, #{outTime,jdbcType=VARCHAR}, ",
        "#{amount,jdbcType=DOUBLE})"
    })
    int insert(TPaymentDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    @InsertProvider(type=TPaymentDetailsSqlProvider.class, method="insertSelective")
    int insertSelective(TPaymentDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    @SelectProvider(type=TPaymentDetailsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="payment_method", property="paymentMethod", jdbcType=JdbcType.INTEGER),
        @Result(column="acquiring_channel", property="acquiringChannel", jdbcType=JdbcType.INTEGER),
        @Result(column="payment_channel", property="paymentChannel", jdbcType=JdbcType.INTEGER),
        @Result(column="payment_order_id", property="paymentOrderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="in_time", property="inTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_time", property="outTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="amount", property="amount", jdbcType=JdbcType.DOUBLE)
    })
    List<TPaymentDetails> selectByExample(TPaymentDetailsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, car_plate, park_id, order_id, payment_method, acquiring_channel, payment_channel, ",
        "payment_order_id, in_time, out_time, amount",
        "from t_payment_details",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="car_plate", property="carPlate", jdbcType=JdbcType.VARCHAR),
        @Result(column="park_id", property="parkId", jdbcType=JdbcType.INTEGER),
        @Result(column="order_id", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="payment_method", property="paymentMethod", jdbcType=JdbcType.INTEGER),
        @Result(column="acquiring_channel", property="acquiringChannel", jdbcType=JdbcType.INTEGER),
        @Result(column="payment_channel", property="paymentChannel", jdbcType=JdbcType.INTEGER),
        @Result(column="payment_order_id", property="paymentOrderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="in_time", property="inTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="out_time", property="outTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="amount", property="amount", jdbcType=JdbcType.DOUBLE)
    })
    TPaymentDetails selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TPaymentDetailsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TPaymentDetails record, @Param("example") TPaymentDetailsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TPaymentDetailsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TPaymentDetails record, @Param("example") TPaymentDetailsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TPaymentDetailsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TPaymentDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_payment_details
     *
     * @mbg.generated
     */
    @Update({
        "update t_payment_details",
        "set car_plate = #{carPlate,jdbcType=VARCHAR},",
          "park_id = #{parkId,jdbcType=INTEGER},",
          "order_id = #{orderId,jdbcType=VARCHAR},",
          "payment_method = #{paymentMethod,jdbcType=INTEGER},",
          "acquiring_channel = #{acquiringChannel,jdbcType=INTEGER},",
          "payment_channel = #{paymentChannel,jdbcType=INTEGER},",
          "payment_order_id = #{paymentOrderId,jdbcType=VARCHAR},",
          "in_time = #{inTime,jdbcType=VARCHAR},",
          "out_time = #{outTime,jdbcType=VARCHAR},",
          "amount = #{amount,jdbcType=DOUBLE}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TPaymentDetails record);
}