package com.common.entity.eparkingCloud;

import com.common.annotation.ExcelTitle;

/**
 * @Author lishuhan
 * @Description:
 * @Date Create in 18:122018-12-10
 * @Modified By:
 */
public class ExcelTCarWalletReport {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_wallet_report.statistics_time
     *
     * @mbg.generated
     */
    private String statisticsTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_wallet_report.need_pay
     *
     * @mbg.generated
     */
    private Double needPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_wallet_report.actual_pay
     *
     * @mbg.generated
     */
    private Double actualPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_wallet_report.use_pay
     *
     * @mbg.generated
     */
    private Double usePay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_wallet_report.total_wallet_banance
     *
     * @mbg.generated
     */
    private Double totalWalletBanance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_car_wallet_report.create_time
     *
     * @mbg.generated
     */
    private String createTime;


    @ExcelTitle(value = "统计时间",order=1)
    public String getStatisticsTime() {
        return statisticsTime;
    }

    public void setStatisticsTime(String statisticsTime) {
        this.statisticsTime = statisticsTime;
    }
    @ExcelTitle(value = "车主钱包充值金额",order=2)
    public Double getNeedPay() {
        return needPay;
    }

    public void setNeedPay(Double needPay) {
        this.needPay = needPay;
    }
    @ExcelTitle(value = "车主钱包实付金额",order=3)
    public Double getActualPay() {
        return actualPay;
    }

    public void setActualPay(Double actualPay) {
        this.actualPay = actualPay;
    }
    @ExcelTitle(value = "车主钱包支付金额",order=4)
    public Double getUsePay() {
        return usePay;
    }
    public void setUsePay(Double usePay) {
        this.usePay = usePay;
    }
    @ExcelTitle(value = "总钱包余额",order=5)
    public Double getTotalWalletBanance() {
        return totalWalletBanance;
    }

    public void setTotalWalletBanance(Double totalWalletBanance) {
        this.totalWalletBanance = totalWalletBanance;
    }
    @ExcelTitle(value = "创建时间",order=6)
    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

}
