package com.common.entity.eparkingCloud;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PwpParkCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    public PwpParkCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIeparkingdbetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankAccountIsNull() {
            addCriterion("bank_account is null");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankAccountIsNotNull() {
            addCriterion("bank_account is not null");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankAccountEqualTo(String value) {
            addCriterion("bank_account =", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankAccountNotEqualTo(String value) {
            addCriterion("bank_account <>", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankAccountGreaterThan(String value) {
            addCriterion("bank_account >", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankAccountGreaterThanOrEqualTo(String value) {
            addCriterion("bank_account >=", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankAccountLessThan(String value) {
            addCriterion("bank_account <", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankAccountLessThanOrEqualTo(String value) {
            addCriterion("bank_account <=", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankAccountLike(String value) {
            addCriterion("bank_account like", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankAccountNotLike(String value) {
            addCriterion("bank_account not like", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankAccountIn(List<String> values) {
            addCriterion("bank_account in", values, "bankAccount");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankAccountNotIn(List<String> values) {
            addCriterion("bank_account not in", values, "bankAccount");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankAccountBetween(String value1, String value2) {
            addCriterion("bank_account between", value1, value2, "bankAccount");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankAccountNotBetween(String value1, String value2) {
            addCriterion("bank_account not between", value1, value2, "bankAccount");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankCardIsNull() {
            addCriterion("bank_card is null");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankCardIsNotNull() {
            addCriterion("bank_card is not null");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankCardEqualTo(String value) {
            addCriterion("bank_card =", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankCardNotEqualTo(String value) {
            addCriterion("bank_card <>", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankCardGreaterThan(String value) {
            addCriterion("bank_card >", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankCardGreaterThanOrEqualTo(String value) {
            addCriterion("bank_card >=", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankCardLessThan(String value) {
            addCriterion("bank_card <", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankCardLessThanOrEqualTo(String value) {
            addCriterion("bank_card <=", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankCardLike(String value) {
            addCriterion("bank_card like", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankCardNotLike(String value) {
            addCriterion("bank_card not like", value, "bankCard");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankCardIn(List<String> values) {
            addCriterion("bank_card in", values, "bankCard");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankCardNotIn(List<String> values) {
            addCriterion("bank_card not in", values, "bankCard");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankCareparkingdbetween(String value1, String value2) {
            addCriterion("bank_card between", value1, value2, "bankCard");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankCardNotBetween(String value1, String value2) {
            addCriterion("bank_card not between", value1, value2, "bankCard");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankNameIsNull() {
            addCriterion("bank_name is null");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankNameIsNotNull() {
            addCriterion("bank_name is not null");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankNameEqualTo(String value) {
            addCriterion("bank_name =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankNameNotEqualTo(String value) {
            addCriterion("bank_name <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankNameGreaterThan(String value) {
            addCriterion("bank_name >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankNameGreaterThanOrEqualTo(String value) {
            addCriterion("bank_name >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankNameLessThan(String value) {
            addCriterion("bank_name <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankNameLessThanOrEqualTo(String value) {
            addCriterion("bank_name <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankNameLike(String value) {
            addCriterion("bank_name like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankNameNotLike(String value) {
            addCriterion("bank_name not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankNameIn(List<String> values) {
            addCriterion("bank_name in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankNameNotIn(List<String> values) {
            addCriterion("bank_name not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankNameBetween(String value1, String value2) {
            addCriterion("bank_name between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria aneparkingdbankNameNotBetween(String value1, String value2) {
            addCriterion("bank_name not between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andDomainIsNull() {
            addCriterion("domain is null");
            return (Criteria) this;
        }

        public Criteria andDomainIsNotNull() {
            addCriterion("domain is not null");
            return (Criteria) this;
        }

        public Criteria andDomainEqualTo(String value) {
            addCriterion("domain =", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotEqualTo(String value) {
            addCriterion("domain <>", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainGreaterThan(String value) {
            addCriterion("domain >", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainGreaterThanOrEqualTo(String value) {
            addCriterion("domain >=", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLessThan(String value) {
            addCriterion("domain <", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLessThanOrEqualTo(String value) {
            addCriterion("domain <=", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLike(String value) {
            addCriterion("domain like", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotLike(String value) {
            addCriterion("domain not like", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainIn(List<String> values) {
            addCriterion("domain in", values, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotIn(List<String> values) {
            addCriterion("domain not in", values, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainBetween(String value1, String value2) {
            addCriterion("domain between", value1, value2, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotBetween(String value1, String value2) {
            addCriterion("domain not between", value1, value2, "domain");
            return (Criteria) this;
        }

        public Criteria andExternalAccountIsNull() {
            addCriterion("external_account is null");
            return (Criteria) this;
        }

        public Criteria andExternalAccountIsNotNull() {
            addCriterion("external_account is not null");
            return (Criteria) this;
        }

        public Criteria andExternalAccountEqualTo(String value) {
            addCriterion("external_account =", value, "externalAccount");
            return (Criteria) this;
        }

        public Criteria andExternalAccountNotEqualTo(String value) {
            addCriterion("external_account <>", value, "externalAccount");
            return (Criteria) this;
        }

        public Criteria andExternalAccountGreaterThan(String value) {
            addCriterion("external_account >", value, "externalAccount");
            return (Criteria) this;
        }

        public Criteria andExternalAccountGreaterThanOrEqualTo(String value) {
            addCriterion("external_account >=", value, "externalAccount");
            return (Criteria) this;
        }

        public Criteria andExternalAccountLessThan(String value) {
            addCriterion("external_account <", value, "externalAccount");
            return (Criteria) this;
        }

        public Criteria andExternalAccountLessThanOrEqualTo(String value) {
            addCriterion("external_account <=", value, "externalAccount");
            return (Criteria) this;
        }

        public Criteria andExternalAccountLike(String value) {
            addCriterion("external_account like", value, "externalAccount");
            return (Criteria) this;
        }

        public Criteria andExternalAccountNotLike(String value) {
            addCriterion("external_account not like", value, "externalAccount");
            return (Criteria) this;
        }

        public Criteria andExternalAccountIn(List<String> values) {
            addCriterion("external_account in", values, "externalAccount");
            return (Criteria) this;
        }

        public Criteria andExternalAccountNotIn(List<String> values) {
            addCriterion("external_account not in", values, "externalAccount");
            return (Criteria) this;
        }

        public Criteria andExternalAccountBetween(String value1, String value2) {
            addCriterion("external_account between", value1, value2, "externalAccount");
            return (Criteria) this;
        }

        public Criteria andExternalAccountNotBetween(String value1, String value2) {
            addCriterion("external_account not between", value1, value2, "externalAccount");
            return (Criteria) this;
        }

        public Criteria andLeagueIdIsNull() {
            addCriterion("league_id is null");
            return (Criteria) this;
        }

        public Criteria andLeagueIdIsNotNull() {
            addCriterion("league_id is not null");
            return (Criteria) this;
        }

        public Criteria andLeagueIdEqualTo(Integer value) {
            addCriterion("league_id =", value, "leagueId");
            return (Criteria) this;
        }

        public Criteria andLeagueIdNotEqualTo(Integer value) {
            addCriterion("league_id <>", value, "leagueId");
            return (Criteria) this;
        }

        public Criteria andLeagueIdGreaterThan(Integer value) {
            addCriterion("league_id >", value, "leagueId");
            return (Criteria) this;
        }

        public Criteria andLeagueIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("league_id >=", value, "leagueId");
            return (Criteria) this;
        }

        public Criteria andLeagueIdLessThan(Integer value) {
            addCriterion("league_id <", value, "leagueId");
            return (Criteria) this;
        }

        public Criteria andLeagueIdLessThanOrEqualTo(Integer value) {
            addCriterion("league_id <=", value, "leagueId");
            return (Criteria) this;
        }

        public Criteria andLeagueIdIn(List<Integer> values) {
            addCriterion("league_id in", values, "leagueId");
            return (Criteria) this;
        }

        public Criteria andLeagueIdNotIn(List<Integer> values) {
            addCriterion("league_id not in", values, "leagueId");
            return (Criteria) this;
        }

        public Criteria andLeagueIeparkingdbetween(Integer value1, Integer value2) {
            addCriterion("league_id between", value1, value2, "leagueId");
            return (Criteria) this;
        }

        public Criteria andLeagueIdNotBetween(Integer value1, Integer value2) {
            addCriterion("league_id not between", value1, value2, "leagueId");
            return (Criteria) this;
        }

        public Criteria andLocalRequestKeyIsNull() {
            addCriterion("local_request_key is null");
            return (Criteria) this;
        }

        public Criteria andLocalRequestKeyIsNotNull() {
            addCriterion("local_request_key is not null");
            return (Criteria) this;
        }

        public Criteria andLocalRequestKeyEqualTo(String value) {
            addCriterion("local_request_key =", value, "localRequestKey");
            return (Criteria) this;
        }

        public Criteria andLocalRequestKeyNotEqualTo(String value) {
            addCriterion("local_request_key <>", value, "localRequestKey");
            return (Criteria) this;
        }

        public Criteria andLocalRequestKeyGreaterThan(String value) {
            addCriterion("local_request_key >", value, "localRequestKey");
            return (Criteria) this;
        }

        public Criteria andLocalRequestKeyGreaterThanOrEqualTo(String value) {
            addCriterion("local_request_key >=", value, "localRequestKey");
            return (Criteria) this;
        }

        public Criteria andLocalRequestKeyLessThan(String value) {
            addCriterion("local_request_key <", value, "localRequestKey");
            return (Criteria) this;
        }

        public Criteria andLocalRequestKeyLessThanOrEqualTo(String value) {
            addCriterion("local_request_key <=", value, "localRequestKey");
            return (Criteria) this;
        }

        public Criteria andLocalRequestKeyLike(String value) {
            addCriterion("local_request_key like", value, "localRequestKey");
            return (Criteria) this;
        }

        public Criteria andLocalRequestKeyNotLike(String value) {
            addCriterion("local_request_key not like", value, "localRequestKey");
            return (Criteria) this;
        }

        public Criteria andLocalRequestKeyIn(List<String> values) {
            addCriterion("local_request_key in", values, "localRequestKey");
            return (Criteria) this;
        }

        public Criteria andLocalRequestKeyNotIn(List<String> values) {
            addCriterion("local_request_key not in", values, "localRequestKey");
            return (Criteria) this;
        }

        public Criteria andLocalRequestKeyBetween(String value1, String value2) {
            addCriterion("local_request_key between", value1, value2, "localRequestKey");
            return (Criteria) this;
        }

        public Criteria andLocalRequestKeyNotBetween(String value1, String value2) {
            addCriterion("local_request_key not between", value1, value2, "localRequestKey");
            return (Criteria) this;
        }

        public Criteria andMonthRuleIsNull() {
            addCriterion("month_rule is null");
            return (Criteria) this;
        }

        public Criteria andMonthRuleIsNotNull() {
            addCriterion("month_rule is not null");
            return (Criteria) this;
        }

        public Criteria andMonthRuleEqualTo(Integer value) {
            addCriterion("month_rule =", value, "monthRule");
            return (Criteria) this;
        }

        public Criteria andMonthRuleNotEqualTo(Integer value) {
            addCriterion("month_rule <>", value, "monthRule");
            return (Criteria) this;
        }

        public Criteria andMonthRuleGreaterThan(Integer value) {
            addCriterion("month_rule >", value, "monthRule");
            return (Criteria) this;
        }

        public Criteria andMonthRuleGreaterThanOrEqualTo(Integer value) {
            addCriterion("month_rule >=", value, "monthRule");
            return (Criteria) this;
        }

        public Criteria andMonthRuleLessThan(Integer value) {
            addCriterion("month_rule <", value, "monthRule");
            return (Criteria) this;
        }

        public Criteria andMonthRuleLessThanOrEqualTo(Integer value) {
            addCriterion("month_rule <=", value, "monthRule");
            return (Criteria) this;
        }

        public Criteria andMonthRuleIn(List<Integer> values) {
            addCriterion("month_rule in", values, "monthRule");
            return (Criteria) this;
        }

        public Criteria andMonthRuleNotIn(List<Integer> values) {
            addCriterion("month_rule not in", values, "monthRule");
            return (Criteria) this;
        }

        public Criteria andMonthRuleBetween(Integer value1, Integer value2) {
            addCriterion("month_rule between", value1, value2, "monthRule");
            return (Criteria) this;
        }

        public Criteria andMonthRuleNotBetween(Integer value1, Integer value2) {
            addCriterion("month_rule not between", value1, value2, "monthRule");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andParkNumIsNull() {
            addCriterion("park_num is null");
            return (Criteria) this;
        }

        public Criteria andParkNumIsNotNull() {
            addCriterion("park_num is not null");
            return (Criteria) this;
        }

        public Criteria andParkNumEqualTo(Integer value) {
            addCriterion("park_num =", value, "parkNum");
            return (Criteria) this;
        }

        public Criteria andParkNumNotEqualTo(Integer value) {
            addCriterion("park_num <>", value, "parkNum");
            return (Criteria) this;
        }

        public Criteria andParkNumGreaterThan(Integer value) {
            addCriterion("park_num >", value, "parkNum");
            return (Criteria) this;
        }

        public Criteria andParkNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("park_num >=", value, "parkNum");
            return (Criteria) this;
        }

        public Criteria andParkNumLessThan(Integer value) {
            addCriterion("park_num <", value, "parkNum");
            return (Criteria) this;
        }

        public Criteria andParkNumLessThanOrEqualTo(Integer value) {
            addCriterion("park_num <=", value, "parkNum");
            return (Criteria) this;
        }

        public Criteria andParkNumIn(List<Integer> values) {
            addCriterion("park_num in", values, "parkNum");
            return (Criteria) this;
        }

        public Criteria andParkNumNotIn(List<Integer> values) {
            addCriterion("park_num not in", values, "parkNum");
            return (Criteria) this;
        }

        public Criteria andParkNumBetween(Integer value1, Integer value2) {
            addCriterion("park_num between", value1, value2, "parkNum");
            return (Criteria) this;
        }

        public Criteria andParkNumNotBetween(Integer value1, Integer value2) {
            addCriterion("park_num not between", value1, value2, "parkNum");
            return (Criteria) this;
        }

        public Criteria andParkPlanIsNull() {
            addCriterion("park_plan is null");
            return (Criteria) this;
        }

        public Criteria andParkPlanIsNotNull() {
            addCriterion("park_plan is not null");
            return (Criteria) this;
        }

        public Criteria andParkPlanEqualTo(String value) {
            addCriterion("park_plan =", value, "parkPlan");
            return (Criteria) this;
        }

        public Criteria andParkPlanNotEqualTo(String value) {
            addCriterion("park_plan <>", value, "parkPlan");
            return (Criteria) this;
        }

        public Criteria andParkPlanGreaterThan(String value) {
            addCriterion("park_plan >", value, "parkPlan");
            return (Criteria) this;
        }

        public Criteria andParkPlanGreaterThanOrEqualTo(String value) {
            addCriterion("park_plan >=", value, "parkPlan");
            return (Criteria) this;
        }

        public Criteria andParkPlanLessThan(String value) {
            addCriterion("park_plan <", value, "parkPlan");
            return (Criteria) this;
        }

        public Criteria andParkPlanLessThanOrEqualTo(String value) {
            addCriterion("park_plan <=", value, "parkPlan");
            return (Criteria) this;
        }

        public Criteria andParkPlanLike(String value) {
            addCriterion("park_plan like", value, "parkPlan");
            return (Criteria) this;
        }

        public Criteria andParkPlanNotLike(String value) {
            addCriterion("park_plan not like", value, "parkPlan");
            return (Criteria) this;
        }

        public Criteria andParkPlanIn(List<String> values) {
            addCriterion("park_plan in", values, "parkPlan");
            return (Criteria) this;
        }

        public Criteria andParkPlanNotIn(List<String> values) {
            addCriterion("park_plan not in", values, "parkPlan");
            return (Criteria) this;
        }

        public Criteria andParkPlanBetween(String value1, String value2) {
            addCriterion("park_plan between", value1, value2, "parkPlan");
            return (Criteria) this;
        }

        public Criteria andParkPlanNotBetween(String value1, String value2) {
            addCriterion("park_plan not between", value1, value2, "parkPlan");
            return (Criteria) this;
        }

        public Criteria andParkStatusIsNull() {
            addCriterion("park_status is null");
            return (Criteria) this;
        }

        public Criteria andParkStatusIsNotNull() {
            addCriterion("park_status is not null");
            return (Criteria) this;
        }

        public Criteria andParkStatusEqualTo(Short value) {
            addCriterion("park_status =", value, "parkStatus");
            return (Criteria) this;
        }

        public Criteria andParkStatusNotEqualTo(Short value) {
            addCriterion("park_status <>", value, "parkStatus");
            return (Criteria) this;
        }

        public Criteria andParkStatusGreaterThan(Short value) {
            addCriterion("park_status >", value, "parkStatus");
            return (Criteria) this;
        }

        public Criteria andParkStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("park_status >=", value, "parkStatus");
            return (Criteria) this;
        }

        public Criteria andParkStatusLessThan(Short value) {
            addCriterion("park_status <", value, "parkStatus");
            return (Criteria) this;
        }

        public Criteria andParkStatusLessThanOrEqualTo(Short value) {
            addCriterion("park_status <=", value, "parkStatus");
            return (Criteria) this;
        }

        public Criteria andParkStatusIn(List<Short> values) {
            addCriterion("park_status in", values, "parkStatus");
            return (Criteria) this;
        }

        public Criteria andParkStatusNotIn(List<Short> values) {
            addCriterion("park_status not in", values, "parkStatus");
            return (Criteria) this;
        }

        public Criteria andParkStatusBetween(Short value1, Short value2) {
            addCriterion("park_status between", value1, value2, "parkStatus");
            return (Criteria) this;
        }

        public Criteria andParkStatusNotBetween(Short value1, Short value2) {
            addCriterion("park_status not between", value1, value2, "parkStatus");
            return (Criteria) this;
        }

        public Criteria andParkTypeIsNull() {
            addCriterion("park_type is null");
            return (Criteria) this;
        }

        public Criteria andParkTypeIsNotNull() {
            addCriterion("park_type is not null");
            return (Criteria) this;
        }

        public Criteria andParkTypeEqualTo(Short value) {
            addCriterion("park_type =", value, "parkType");
            return (Criteria) this;
        }

        public Criteria andParkTypeNotEqualTo(Short value) {
            addCriterion("park_type <>", value, "parkType");
            return (Criteria) this;
        }

        public Criteria andParkTypeGreaterThan(Short value) {
            addCriterion("park_type >", value, "parkType");
            return (Criteria) this;
        }

        public Criteria andParkTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("park_type >=", value, "parkType");
            return (Criteria) this;
        }

        public Criteria andParkTypeLessThan(Short value) {
            addCriterion("park_type <", value, "parkType");
            return (Criteria) this;
        }

        public Criteria andParkTypeLessThanOrEqualTo(Short value) {
            addCriterion("park_type <=", value, "parkType");
            return (Criteria) this;
        }

        public Criteria andParkTypeIn(List<Short> values) {
            addCriterion("park_type in", values, "parkType");
            return (Criteria) this;
        }

        public Criteria andParkTypeNotIn(List<Short> values) {
            addCriterion("park_type not in", values, "parkType");
            return (Criteria) this;
        }

        public Criteria andParkTypeBetween(Short value1, Short value2) {
            addCriterion("park_type between", value1, value2, "parkType");
            return (Criteria) this;
        }

        public Criteria andParkTypeNotBetween(Short value1, Short value2) {
            addCriterion("park_type not between", value1, value2, "parkType");
            return (Criteria) this;
        }

        public Criteria andPhotoIsNull() {
            addCriterion("photo is null");
            return (Criteria) this;
        }

        public Criteria andPhotoIsNotNull() {
            addCriterion("photo is not null");
            return (Criteria) this;
        }

        public Criteria andPhotoEqualTo(String value) {
            addCriterion("photo =", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotEqualTo(String value) {
            addCriterion("photo <>", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoGreaterThan(String value) {
            addCriterion("photo >", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoGreaterThanOrEqualTo(String value) {
            addCriterion("photo >=", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoLessThan(String value) {
            addCriterion("photo <", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoLessThanOrEqualTo(String value) {
            addCriterion("photo <=", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoLike(String value) {
            addCriterion("photo like", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotLike(String value) {
            addCriterion("photo not like", value, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoIn(List<String> values) {
            addCriterion("photo in", values, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotIn(List<String> values) {
            addCriterion("photo not in", values, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoBetween(String value1, String value2) {
            addCriterion("photo between", value1, value2, "photo");
            return (Criteria) this;
        }

        public Criteria andPhotoNotBetween(String value1, String value2) {
            addCriterion("photo not between", value1, value2, "photo");
            return (Criteria) this;
        }

        public Criteria andPositionXIsNull() {
            addCriterion("position_x is null");
            return (Criteria) this;
        }

        public Criteria andPositionXIsNotNull() {
            addCriterion("position_x is not null");
            return (Criteria) this;
        }

        public Criteria andPositionXEqualTo(String value) {
            addCriterion("position_x =", value, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXNotEqualTo(String value) {
            addCriterion("position_x <>", value, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXGreaterThan(String value) {
            addCriterion("position_x >", value, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXGreaterThanOrEqualTo(String value) {
            addCriterion("position_x >=", value, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXLessThan(String value) {
            addCriterion("position_x <", value, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXLessThanOrEqualTo(String value) {
            addCriterion("position_x <=", value, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXLike(String value) {
            addCriterion("position_x like", value, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXNotLike(String value) {
            addCriterion("position_x not like", value, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXIn(List<String> values) {
            addCriterion("position_x in", values, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXNotIn(List<String> values) {
            addCriterion("position_x not in", values, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXBetween(String value1, String value2) {
            addCriterion("position_x between", value1, value2, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionXNotBetween(String value1, String value2) {
            addCriterion("position_x not between", value1, value2, "positionX");
            return (Criteria) this;
        }

        public Criteria andPositionYIsNull() {
            addCriterion("position_y is null");
            return (Criteria) this;
        }

        public Criteria andPositionYIsNotNull() {
            addCriterion("position_y is not null");
            return (Criteria) this;
        }

        public Criteria andPositionYEqualTo(String value) {
            addCriterion("position_y =", value, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYNotEqualTo(String value) {
            addCriterion("position_y <>", value, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYGreaterThan(String value) {
            addCriterion("position_y >", value, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYGreaterThanOrEqualTo(String value) {
            addCriterion("position_y >=", value, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYLessThan(String value) {
            addCriterion("position_y <", value, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYLessThanOrEqualTo(String value) {
            addCriterion("position_y <=", value, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYLike(String value) {
            addCriterion("position_y like", value, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYNotLike(String value) {
            addCriterion("position_y not like", value, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYIn(List<String> values) {
            addCriterion("position_y in", values, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYNotIn(List<String> values) {
            addCriterion("position_y not in", values, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYBetween(String value1, String value2) {
            addCriterion("position_y between", value1, value2, "positionY");
            return (Criteria) this;
        }

        public Criteria andPositionYNotBetween(String value1, String value2) {
            addCriterion("position_y not between", value1, value2, "positionY");
            return (Criteria) this;
        }

        public Criteria andSystemRatioIsNull() {
            addCriterion("system_ratio is null");
            return (Criteria) this;
        }

        public Criteria andSystemRatioIsNotNull() {
            addCriterion("system_ratio is not null");
            return (Criteria) this;
        }

        public Criteria andSystemRatioEqualTo(Double value) {
            addCriterion("system_ratio =", value, "systemRatio");
            return (Criteria) this;
        }

        public Criteria andSystemRatioNotEqualTo(Double value) {
            addCriterion("system_ratio <>", value, "systemRatio");
            return (Criteria) this;
        }

        public Criteria andSystemRatioGreaterThan(Double value) {
            addCriterion("system_ratio >", value, "systemRatio");
            return (Criteria) this;
        }

        public Criteria andSystemRatioGreaterThanOrEqualTo(Double value) {
            addCriterion("system_ratio >=", value, "systemRatio");
            return (Criteria) this;
        }

        public Criteria andSystemRatioLessThan(Double value) {
            addCriterion("system_ratio <", value, "systemRatio");
            return (Criteria) this;
        }

        public Criteria andSystemRatioLessThanOrEqualTo(Double value) {
            addCriterion("system_ratio <=", value, "systemRatio");
            return (Criteria) this;
        }

        public Criteria andSystemRatioIn(List<Double> values) {
            addCriterion("system_ratio in", values, "systemRatio");
            return (Criteria) this;
        }

        public Criteria andSystemRatioNotIn(List<Double> values) {
            addCriterion("system_ratio not in", values, "systemRatio");
            return (Criteria) this;
        }

        public Criteria andSystemRatioBetween(Double value1, Double value2) {
            addCriterion("system_ratio between", value1, value2, "systemRatio");
            return (Criteria) this;
        }

        public Criteria andSystemRatioNotBetween(Double value1, Double value2) {
            addCriterion("system_ratio not between", value1, value2, "systemRatio");
            return (Criteria) this;
        }

        public Criteria andTotalNumIsNull() {
            addCriterion("total_num is null");
            return (Criteria) this;
        }

        public Criteria andTotalNumIsNotNull() {
            addCriterion("total_num is not null");
            return (Criteria) this;
        }

        public Criteria andTotalNumEqualTo(Integer value) {
            addCriterion("total_num =", value, "totalNum");
            return (Criteria) this;
        }

        public Criteria andTotalNumNotEqualTo(Integer value) {
            addCriterion("total_num <>", value, "totalNum");
            return (Criteria) this;
        }

        public Criteria andTotalNumGreaterThan(Integer value) {
            addCriterion("total_num >", value, "totalNum");
            return (Criteria) this;
        }

        public Criteria andTotalNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_num >=", value, "totalNum");
            return (Criteria) this;
        }

        public Criteria andTotalNumLessThan(Integer value) {
            addCriterion("total_num <", value, "totalNum");
            return (Criteria) this;
        }

        public Criteria andTotalNumLessThanOrEqualTo(Integer value) {
            addCriterion("total_num <=", value, "totalNum");
            return (Criteria) this;
        }

        public Criteria andTotalNumIn(List<Integer> values) {
            addCriterion("total_num in", values, "totalNum");
            return (Criteria) this;
        }

        public Criteria andTotalNumNotIn(List<Integer> values) {
            addCriterion("total_num not in", values, "totalNum");
            return (Criteria) this;
        }

        public Criteria andTotalNumBetween(Integer value1, Integer value2) {
            addCriterion("total_num between", value1, value2, "totalNum");
            return (Criteria) this;
        }

        public Criteria andTotalNumNotBetween(Integer value1, Integer value2) {
            addCriterion("total_num not between", value1, value2, "totalNum");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pwp_park
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pwp_park
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}