package com.common.entity.eparkingCloud;

public class TIpc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ipc.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ipc.ipc_type
     *
     * @mbg.generated
     */
    private Integer ipcType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ipc.rtspUrl
     *
     * @mbg.generated
     */
    private String rtspurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_ipc.相机厂家名称
     *
     * @mbg.generated
     */
    private String 相机厂家名称;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ipc.id
     *
     * @return the value of t_ipc.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ipc.id
     *
     * @param id the value for t_ipc.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ipc.ipc_type
     *
     * @return the value of t_ipc.ipc_type
     *
     * @mbg.generated
     */
    public Integer getIpcType() {
        return ipcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ipc.ipc_type
     *
     * @param ipcType the value for t_ipc.ipc_type
     *
     * @mbg.generated
     */
    public void setIpcType(Integer ipcType) {
        this.ipcType = ipcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ipc.rtspUrl
     *
     * @return the value of t_ipc.rtspUrl
     *
     * @mbg.generated
     */
    public String getRtspurl() {
        return rtspurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ipc.rtspUrl
     *
     * @param rtspurl the value for t_ipc.rtspUrl
     *
     * @mbg.generated
     */
    public void setRtspurl(String rtspurl) {
        this.rtspurl = rtspurl == null ? null : rtspurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_ipc.相机厂家名称
     *
     * @return the value of t_ipc.相机厂家名称
     *
     * @mbg.generated
     */
    public String get相机厂家名称() {
        return 相机厂家名称;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_ipc.相机厂家名称
     *
     * @param 相机厂家名称 the value for t_ipc.相机厂家名称
     *
     * @mbg.generated
     */
    public void set相机厂家名称(String 相机厂家名称) {
        this.相机厂家名称 = 相机厂家名称 == null ? null : 相机厂家名称.trim();
    }
}