package com.common.entity.eparkingCloud;

public class TParkPort {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.park_id
     *
     * @mbg.generated
     */
    private Integer parkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.port_id
     *
     * @mbg.generated
     */
    private Integer portId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.port_name
     *
     * @mbg.generated
     */
    private String portName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.port_type
     *
     * @mbg.generated
     */
    private Integer portType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.computer_index
     *
     * @mbg.generated
     */
    private String computerIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.park_name
     *
     * @mbg.generated
     */
    private String parkName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.lane_control_sn
     *
     * @mbg.generated
     */
    private String laneControlSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.ipc_ip
     *
     * @mbg.generated
     */
    private String ipcIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.ipc_sn
     *
     * @mbg.generated
     */
    private String ipcSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.aux_ipc1_sn
     *
     * @mbg.generated
     */
    private String auxIpc1Sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.aux_ipc2_sn
     *
     * @mbg.generated
     */
    private String auxIpc2Sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.area_number
     *
     * @mbg.generated
     */
    private Integer areaNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.intervene
     *
     * @mbg.generated
     */
    private Integer intervene;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.actived
     *
     * @mbg.generated
     */
    private Integer actived;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.lots_led_ip
     *
     * @mbg.generated
     */
    private String lotsLedIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.lots_led_str
     *
     * @mbg.generated
     */
    private String lotsLedStr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.is_in_car_update
     *
     * @mbg.generated
     */
    private Integer isInCarUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.lane_rx_mode
     *
     * @mbg.generated
     */
    private Integer laneRxMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.voice_mode
     *
     * @mbg.generated
     */
    private Integer voiceMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.voice_volume
     *
     * @mbg.generated
     */
    private Integer voiceVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_port.ipc_type
     *
     * @mbg.generated
     */
    private Integer ipcType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.id
     *
     * @return the value of t_park_port.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.id
     *
     * @param id the value for t_park_port.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.park_id
     *
     * @return the value of t_park_port.park_id
     *
     * @mbg.generated
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.park_id
     *
     * @param parkId the value for t_park_port.park_id
     *
     * @mbg.generated
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.port_id
     *
     * @return the value of t_park_port.port_id
     *
     * @mbg.generated
     */
    public Integer getPortId() {
        return portId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.port_id
     *
     * @param portId the value for t_park_port.port_id
     *
     * @mbg.generated
     */
    public void setPortId(Integer portId) {
        this.portId = portId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.port_name
     *
     * @return the value of t_park_port.port_name
     *
     * @mbg.generated
     */
    public String getPortName() {
        return portName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.port_name
     *
     * @param portName the value for t_park_port.port_name
     *
     * @mbg.generated
     */
    public void setPortName(String portName) {
        this.portName = portName == null ? null : portName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.port_type
     *
     * @return the value of t_park_port.port_type
     *
     * @mbg.generated
     */
    public Integer getPortType() {
        return portType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.port_type
     *
     * @param portType the value for t_park_port.port_type
     *
     * @mbg.generated
     */
    public void setPortType(Integer portType) {
        this.portType = portType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.computer_index
     *
     * @return the value of t_park_port.computer_index
     *
     * @mbg.generated
     */
    public String getComputerIndex() {
        return computerIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.computer_index
     *
     * @param computerIndex the value for t_park_port.computer_index
     *
     * @mbg.generated
     */
    public void setComputerIndex(String computerIndex) {
        this.computerIndex = computerIndex == null ? null : computerIndex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.park_name
     *
     * @return the value of t_park_port.park_name
     *
     * @mbg.generated
     */
    public String getParkName() {
        return parkName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.park_name
     *
     * @param parkName the value for t_park_port.park_name
     *
     * @mbg.generated
     */
    public void setParkName(String parkName) {
        this.parkName = parkName == null ? null : parkName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.lane_control_sn
     *
     * @return the value of t_park_port.lane_control_sn
     *
     * @mbg.generated
     */
    public String getLaneControlSn() {
        return laneControlSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.lane_control_sn
     *
     * @param laneControlSn the value for t_park_port.lane_control_sn
     *
     * @mbg.generated
     */
    public void setLaneControlSn(String laneControlSn) {
        this.laneControlSn = laneControlSn == null ? null : laneControlSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.ipc_ip
     *
     * @return the value of t_park_port.ipc_ip
     *
     * @mbg.generated
     */
    public String getIpcIp() {
        return ipcIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.ipc_ip
     *
     * @param ipcIp the value for t_park_port.ipc_ip
     *
     * @mbg.generated
     */
    public void setIpcIp(String ipcIp) {
        this.ipcIp = ipcIp == null ? null : ipcIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.ipc_sn
     *
     * @return the value of t_park_port.ipc_sn
     *
     * @mbg.generated
     */
    public String getIpcSn() {
        return ipcSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.ipc_sn
     *
     * @param ipcSn the value for t_park_port.ipc_sn
     *
     * @mbg.generated
     */
    public void setIpcSn(String ipcSn) {
        this.ipcSn = ipcSn == null ? null : ipcSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.aux_ipc1_sn
     *
     * @return the value of t_park_port.aux_ipc1_sn
     *
     * @mbg.generated
     */
    public String getAuxIpc1Sn() {
        return auxIpc1Sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.aux_ipc1_sn
     *
     * @param auxIpc1Sn the value for t_park_port.aux_ipc1_sn
     *
     * @mbg.generated
     */
    public void setAuxIpc1Sn(String auxIpc1Sn) {
        this.auxIpc1Sn = auxIpc1Sn == null ? null : auxIpc1Sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.aux_ipc2_sn
     *
     * @return the value of t_park_port.aux_ipc2_sn
     *
     * @mbg.generated
     */
    public String getAuxIpc2Sn() {
        return auxIpc2Sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.aux_ipc2_sn
     *
     * @param auxIpc2Sn the value for t_park_port.aux_ipc2_sn
     *
     * @mbg.generated
     */
    public void setAuxIpc2Sn(String auxIpc2Sn) {
        this.auxIpc2Sn = auxIpc2Sn == null ? null : auxIpc2Sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.area_number
     *
     * @return the value of t_park_port.area_number
     *
     * @mbg.generated
     */
    public Integer getAreaNumber() {
        return areaNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.area_number
     *
     * @param areaNumber the value for t_park_port.area_number
     *
     * @mbg.generated
     */
    public void setAreaNumber(Integer areaNumber) {
        this.areaNumber = areaNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.intervene
     *
     * @return the value of t_park_port.intervene
     *
     * @mbg.generated
     */
    public Integer getIntervene() {
        return intervene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.intervene
     *
     * @param intervene the value for t_park_port.intervene
     *
     * @mbg.generated
     */
    public void setIntervene(Integer intervene) {
        this.intervene = intervene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.actived
     *
     * @return the value of t_park_port.actived
     *
     * @mbg.generated
     */
    public Integer getActived() {
        return actived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.actived
     *
     * @param actived the value for t_park_port.actived
     *
     * @mbg.generated
     */
    public void setActived(Integer actived) {
        this.actived = actived;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.lots_led_ip
     *
     * @return the value of t_park_port.lots_led_ip
     *
     * @mbg.generated
     */
    public String getLotsLedIp() {
        return lotsLedIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.lots_led_ip
     *
     * @param lotsLedIp the value for t_park_port.lots_led_ip
     *
     * @mbg.generated
     */
    public void setLotsLedIp(String lotsLedIp) {
        this.lotsLedIp = lotsLedIp == null ? null : lotsLedIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.lots_led_str
     *
     * @return the value of t_park_port.lots_led_str
     *
     * @mbg.generated
     */
    public String getLotsLedStr() {
        return lotsLedStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.lots_led_str
     *
     * @param lotsLedStr the value for t_park_port.lots_led_str
     *
     * @mbg.generated
     */
    public void setLotsLedStr(String lotsLedStr) {
        this.lotsLedStr = lotsLedStr == null ? null : lotsLedStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.is_in_car_update
     *
     * @return the value of t_park_port.is_in_car_update
     *
     * @mbg.generated
     */
    public Integer getIsInCarUpdate() {
        return isInCarUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.is_in_car_update
     *
     * @param isInCarUpdate the value for t_park_port.is_in_car_update
     *
     * @mbg.generated
     */
    public void setIsInCarUpdate(Integer isInCarUpdate) {
        this.isInCarUpdate = isInCarUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.lane_rx_mode
     *
     * @return the value of t_park_port.lane_rx_mode
     *
     * @mbg.generated
     */
    public Integer getLaneRxMode() {
        return laneRxMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.lane_rx_mode
     *
     * @param laneRxMode the value for t_park_port.lane_rx_mode
     *
     * @mbg.generated
     */
    public void setLaneRxMode(Integer laneRxMode) {
        this.laneRxMode = laneRxMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.voice_mode
     *
     * @return the value of t_park_port.voice_mode
     *
     * @mbg.generated
     */
    public Integer getVoiceMode() {
        return voiceMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.voice_mode
     *
     * @param voiceMode the value for t_park_port.voice_mode
     *
     * @mbg.generated
     */
    public void setVoiceMode(Integer voiceMode) {
        this.voiceMode = voiceMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.voice_volume
     *
     * @return the value of t_park_port.voice_volume
     *
     * @mbg.generated
     */
    public Integer getVoiceVolume() {
        return voiceVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.voice_volume
     *
     * @param voiceVolume the value for t_park_port.voice_volume
     *
     * @mbg.generated
     */
    public void setVoiceVolume(Integer voiceVolume) {
        this.voiceVolume = voiceVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_port.ipc_type
     *
     * @return the value of t_park_port.ipc_type
     *
     * @mbg.generated
     */
    public Integer getIpcType() {
        return ipcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_port.ipc_type
     *
     * @param ipcType the value for t_park_port.ipc_type
     *
     * @mbg.generated
     */
    public void setIpcType(Integer ipcType) {
        this.ipcType = ipcType;
    }
}