package com.common.entity.eparkingCloud;

public class TParkInOutToday {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.actual_pay
     *
     * @mbg.generated
     */
    private Double actualPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.before_pay
     *
     * @mbg.generated
     */
    private Double beforePay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.car_nature
     *
     * @mbg.generated
     */
    private Integer carNature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.charge_type
     *
     * @mbg.generated
     */
    private Integer chargeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.in_car_plate
     *
     * @mbg.generated
     */
    private String inCarPlate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.in_card_code
     *
     * @mbg.generated
     */
    private String inCardCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.in_pic_path
     *
     * @mbg.generated
     */
    private String inPicPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.in_port_id
     *
     * @mbg.generated
     */
    private Integer inPortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.in_port_name
     *
     * @mbg.generated
     */
    private String inPortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.in_time
     *
     * @mbg.generated
     */
    private String inTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.in_type
     *
     * @mbg.generated
     */
    private Integer inType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.in_type_desc
     *
     * @mbg.generated
     */
    private String inTypeDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.need_pay
     *
     * @mbg.generated
     */
    private Double needPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.occur_time
     *
     * @mbg.generated
     */
    private String occurTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.out_car_plate
     *
     * @mbg.generated
     */
    private String outCarPlate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.out_car_type
     *
     * @mbg.generated
     */
    private Integer outCarType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.out_card_code
     *
     * @mbg.generated
     */
    private String outCardCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.out_pic_path
     *
     * @mbg.generated
     */
    private String outPicPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.out_port_id
     *
     * @mbg.generated
     */
    private Integer outPortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.out_port_name
     *
     * @mbg.generated
     */
    private String outPortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.out_time
     *
     * @mbg.generated
     */
    private String outTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.out_type
     *
     * @mbg.generated
     */
    private Integer outType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.out_type_desc
     *
     * @mbg.generated
     */
    private String outTypeDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.park_id
     *
     * @mbg.generated
     */
    private Integer parkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.stop_time
     *
     * @mbg.generated
     */
    private String stopTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.in_split_time
     *
     * @mbg.generated
     */
    private String inSplitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.out_split_time
     *
     * @mbg.generated
     */
    private String outSplitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.first_in_time
     *
     * @mbg.generated
     */
    private String firstInTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.day_pay
     *
     * @mbg.generated
     */
    private Double dayPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.operating_id
     *
     * @mbg.generated
     */
    private Integer operatingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.operating_name
     *
     * @mbg.generated
     */
    private String operatingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.coupon
     *
     * @mbg.generated
     */
    private Double coupon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.qpass_pay
     *
     * @mbg.generated
     */
    private Double qpassPay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.merchant_id
     *
     * @mbg.generated
     */
    private Integer merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.secTime_Payed
     *
     * @mbg.generated
     */
    private Double sectimePayed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.secTime_Start
     *
     * @mbg.generated
     */
    private String sectimeStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.ePayType
     *
     * @mbg.generated
     */
    private Integer epaytype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.statistics_flog
     *
     * @mbg.generated
     */
    private Integer statisticsFlog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.inOut_status
     *
     * @mbg.generated
     */
    private Integer inoutStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.coupon_type
     *
     * @mbg.generated
     */
    private Integer couponType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_park_in_out_today.billing_status
     *
     * @mbg.generated
     */
    private String billingStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.id
     *
     * @return the value of t_park_in_out_today.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.id
     *
     * @param id the value for t_park_in_out_today.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.actual_pay
     *
     * @return the value of t_park_in_out_today.actual_pay
     *
     * @mbg.generated
     */
    public Double getActualPay() {
        return actualPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.actual_pay
     *
     * @param actualPay the value for t_park_in_out_today.actual_pay
     *
     * @mbg.generated
     */
    public void setActualPay(Double actualPay) {
        this.actualPay = actualPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.before_pay
     *
     * @return the value of t_park_in_out_today.before_pay
     *
     * @mbg.generated
     */
    public Double getBeforePay() {
        return beforePay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.before_pay
     *
     * @param beforePay the value for t_park_in_out_today.before_pay
     *
     * @mbg.generated
     */
    public void setBeforePay(Double beforePay) {
        this.beforePay = beforePay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.car_nature
     *
     * @return the value of t_park_in_out_today.car_nature
     *
     * @mbg.generated
     */
    public Integer getCarNature() {
        return carNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.car_nature
     *
     * @param carNature the value for t_park_in_out_today.car_nature
     *
     * @mbg.generated
     */
    public void setCarNature(Integer carNature) {
        this.carNature = carNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.charge_type
     *
     * @return the value of t_park_in_out_today.charge_type
     *
     * @mbg.generated
     */
    public Integer getChargeType() {
        return chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.charge_type
     *
     * @param chargeType the value for t_park_in_out_today.charge_type
     *
     * @mbg.generated
     */
    public void setChargeType(Integer chargeType) {
        this.chargeType = chargeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.company_id
     *
     * @return the value of t_park_in_out_today.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.company_id
     *
     * @param companyId the value for t_park_in_out_today.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.in_car_plate
     *
     * @return the value of t_park_in_out_today.in_car_plate
     *
     * @mbg.generated
     */
    public String getInCarPlate() {
        return inCarPlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.in_car_plate
     *
     * @param inCarPlate the value for t_park_in_out_today.in_car_plate
     *
     * @mbg.generated
     */
    public void setInCarPlate(String inCarPlate) {
        this.inCarPlate = inCarPlate == null ? null : inCarPlate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.in_card_code
     *
     * @return the value of t_park_in_out_today.in_card_code
     *
     * @mbg.generated
     */
    public String getInCardCode() {
        return inCardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.in_card_code
     *
     * @param inCardCode the value for t_park_in_out_today.in_card_code
     *
     * @mbg.generated
     */
    public void setInCardCode(String inCardCode) {
        this.inCardCode = inCardCode == null ? null : inCardCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.in_pic_path
     *
     * @return the value of t_park_in_out_today.in_pic_path
     *
     * @mbg.generated
     */
    public String getInPicPath() {
        return inPicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.in_pic_path
     *
     * @param inPicPath the value for t_park_in_out_today.in_pic_path
     *
     * @mbg.generated
     */
    public void setInPicPath(String inPicPath) {
        this.inPicPath = inPicPath == null ? null : inPicPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.in_port_id
     *
     * @return the value of t_park_in_out_today.in_port_id
     *
     * @mbg.generated
     */
    public Integer getInPortId() {
        return inPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.in_port_id
     *
     * @param inPortId the value for t_park_in_out_today.in_port_id
     *
     * @mbg.generated
     */
    public void setInPortId(Integer inPortId) {
        this.inPortId = inPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.in_port_name
     *
     * @return the value of t_park_in_out_today.in_port_name
     *
     * @mbg.generated
     */
    public String getInPortName() {
        return inPortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.in_port_name
     *
     * @param inPortName the value for t_park_in_out_today.in_port_name
     *
     * @mbg.generated
     */
    public void setInPortName(String inPortName) {
        this.inPortName = inPortName == null ? null : inPortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.in_time
     *
     * @return the value of t_park_in_out_today.in_time
     *
     * @mbg.generated
     */
    public String getInTime() {
        return inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.in_time
     *
     * @param inTime the value for t_park_in_out_today.in_time
     *
     * @mbg.generated
     */
    public void setInTime(String inTime) {
        this.inTime = inTime == null ? null : inTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.in_type
     *
     * @return the value of t_park_in_out_today.in_type
     *
     * @mbg.generated
     */
    public Integer getInType() {
        return inType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.in_type
     *
     * @param inType the value for t_park_in_out_today.in_type
     *
     * @mbg.generated
     */
    public void setInType(Integer inType) {
        this.inType = inType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.in_type_desc
     *
     * @return the value of t_park_in_out_today.in_type_desc
     *
     * @mbg.generated
     */
    public String getInTypeDesc() {
        return inTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.in_type_desc
     *
     * @param inTypeDesc the value for t_park_in_out_today.in_type_desc
     *
     * @mbg.generated
     */
    public void setInTypeDesc(String inTypeDesc) {
        this.inTypeDesc = inTypeDesc == null ? null : inTypeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.need_pay
     *
     * @return the value of t_park_in_out_today.need_pay
     *
     * @mbg.generated
     */
    public Double getNeedPay() {
        return needPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.need_pay
     *
     * @param needPay the value for t_park_in_out_today.need_pay
     *
     * @mbg.generated
     */
    public void setNeedPay(Double needPay) {
        this.needPay = needPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.occur_time
     *
     * @return the value of t_park_in_out_today.occur_time
     *
     * @mbg.generated
     */
    public String getOccurTime() {
        return occurTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.occur_time
     *
     * @param occurTime the value for t_park_in_out_today.occur_time
     *
     * @mbg.generated
     */
    public void setOccurTime(String occurTime) {
        this.occurTime = occurTime == null ? null : occurTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.out_car_plate
     *
     * @return the value of t_park_in_out_today.out_car_plate
     *
     * @mbg.generated
     */
    public String getOutCarPlate() {
        return outCarPlate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.out_car_plate
     *
     * @param outCarPlate the value for t_park_in_out_today.out_car_plate
     *
     * @mbg.generated
     */
    public void setOutCarPlate(String outCarPlate) {
        this.outCarPlate = outCarPlate == null ? null : outCarPlate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.out_car_type
     *
     * @return the value of t_park_in_out_today.out_car_type
     *
     * @mbg.generated
     */
    public Integer getOutCarType() {
        return outCarType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.out_car_type
     *
     * @param outCarType the value for t_park_in_out_today.out_car_type
     *
     * @mbg.generated
     */
    public void setOutCarType(Integer outCarType) {
        this.outCarType = outCarType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.out_card_code
     *
     * @return the value of t_park_in_out_today.out_card_code
     *
     * @mbg.generated
     */
    public String getOutCardCode() {
        return outCardCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.out_card_code
     *
     * @param outCardCode the value for t_park_in_out_today.out_card_code
     *
     * @mbg.generated
     */
    public void setOutCardCode(String outCardCode) {
        this.outCardCode = outCardCode == null ? null : outCardCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.out_pic_path
     *
     * @return the value of t_park_in_out_today.out_pic_path
     *
     * @mbg.generated
     */
    public String getOutPicPath() {
        return outPicPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.out_pic_path
     *
     * @param outPicPath the value for t_park_in_out_today.out_pic_path
     *
     * @mbg.generated
     */
    public void setOutPicPath(String outPicPath) {
        this.outPicPath = outPicPath == null ? null : outPicPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.out_port_id
     *
     * @return the value of t_park_in_out_today.out_port_id
     *
     * @mbg.generated
     */
    public Integer getOutPortId() {
        return outPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.out_port_id
     *
     * @param outPortId the value for t_park_in_out_today.out_port_id
     *
     * @mbg.generated
     */
    public void setOutPortId(Integer outPortId) {
        this.outPortId = outPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.out_port_name
     *
     * @return the value of t_park_in_out_today.out_port_name
     *
     * @mbg.generated
     */
    public String getOutPortName() {
        return outPortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.out_port_name
     *
     * @param outPortName the value for t_park_in_out_today.out_port_name
     *
     * @mbg.generated
     */
    public void setOutPortName(String outPortName) {
        this.outPortName = outPortName == null ? null : outPortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.out_time
     *
     * @return the value of t_park_in_out_today.out_time
     *
     * @mbg.generated
     */
    public String getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.out_time
     *
     * @param outTime the value for t_park_in_out_today.out_time
     *
     * @mbg.generated
     */
    public void setOutTime(String outTime) {
        this.outTime = outTime == null ? null : outTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.out_type
     *
     * @return the value of t_park_in_out_today.out_type
     *
     * @mbg.generated
     */
    public Integer getOutType() {
        return outType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.out_type
     *
     * @param outType the value for t_park_in_out_today.out_type
     *
     * @mbg.generated
     */
    public void setOutType(Integer outType) {
        this.outType = outType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.out_type_desc
     *
     * @return the value of t_park_in_out_today.out_type_desc
     *
     * @mbg.generated
     */
    public String getOutTypeDesc() {
        return outTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.out_type_desc
     *
     * @param outTypeDesc the value for t_park_in_out_today.out_type_desc
     *
     * @mbg.generated
     */
    public void setOutTypeDesc(String outTypeDesc) {
        this.outTypeDesc = outTypeDesc == null ? null : outTypeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.park_id
     *
     * @return the value of t_park_in_out_today.park_id
     *
     * @mbg.generated
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.park_id
     *
     * @param parkId the value for t_park_in_out_today.park_id
     *
     * @mbg.generated
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.stop_time
     *
     * @return the value of t_park_in_out_today.stop_time
     *
     * @mbg.generated
     */
    public String getStopTime() {
        return stopTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.stop_time
     *
     * @param stopTime the value for t_park_in_out_today.stop_time
     *
     * @mbg.generated
     */
    public void setStopTime(String stopTime) {
        this.stopTime = stopTime == null ? null : stopTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.in_split_time
     *
     * @return the value of t_park_in_out_today.in_split_time
     *
     * @mbg.generated
     */
    public String getInSplitTime() {
        return inSplitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.in_split_time
     *
     * @param inSplitTime the value for t_park_in_out_today.in_split_time
     *
     * @mbg.generated
     */
    public void setInSplitTime(String inSplitTime) {
        this.inSplitTime = inSplitTime == null ? null : inSplitTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.out_split_time
     *
     * @return the value of t_park_in_out_today.out_split_time
     *
     * @mbg.generated
     */
    public String getOutSplitTime() {
        return outSplitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.out_split_time
     *
     * @param outSplitTime the value for t_park_in_out_today.out_split_time
     *
     * @mbg.generated
     */
    public void setOutSplitTime(String outSplitTime) {
        this.outSplitTime = outSplitTime == null ? null : outSplitTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.first_in_time
     *
     * @return the value of t_park_in_out_today.first_in_time
     *
     * @mbg.generated
     */
    public String getFirstInTime() {
        return firstInTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.first_in_time
     *
     * @param firstInTime the value for t_park_in_out_today.first_in_time
     *
     * @mbg.generated
     */
    public void setFirstInTime(String firstInTime) {
        this.firstInTime = firstInTime == null ? null : firstInTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.day_pay
     *
     * @return the value of t_park_in_out_today.day_pay
     *
     * @mbg.generated
     */
    public Double getDayPay() {
        return dayPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.day_pay
     *
     * @param dayPay the value for t_park_in_out_today.day_pay
     *
     * @mbg.generated
     */
    public void setDayPay(Double dayPay) {
        this.dayPay = dayPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.operating_id
     *
     * @return the value of t_park_in_out_today.operating_id
     *
     * @mbg.generated
     */
    public Integer getOperatingId() {
        return operatingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.operating_id
     *
     * @param operatingId the value for t_park_in_out_today.operating_id
     *
     * @mbg.generated
     */
    public void setOperatingId(Integer operatingId) {
        this.operatingId = operatingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.operating_name
     *
     * @return the value of t_park_in_out_today.operating_name
     *
     * @mbg.generated
     */
    public String getOperatingName() {
        return operatingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.operating_name
     *
     * @param operatingName the value for t_park_in_out_today.operating_name
     *
     * @mbg.generated
     */
    public void setOperatingName(String operatingName) {
        this.operatingName = operatingName == null ? null : operatingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.coupon
     *
     * @return the value of t_park_in_out_today.coupon
     *
     * @mbg.generated
     */
    public Double getCoupon() {
        return coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.coupon
     *
     * @param coupon the value for t_park_in_out_today.coupon
     *
     * @mbg.generated
     */
    public void setCoupon(Double coupon) {
        this.coupon = coupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.qpass_pay
     *
     * @return the value of t_park_in_out_today.qpass_pay
     *
     * @mbg.generated
     */
    public Double getQpassPay() {
        return qpassPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.qpass_pay
     *
     * @param qpassPay the value for t_park_in_out_today.qpass_pay
     *
     * @mbg.generated
     */
    public void setQpassPay(Double qpassPay) {
        this.qpassPay = qpassPay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.merchant_id
     *
     * @return the value of t_park_in_out_today.merchant_id
     *
     * @mbg.generated
     */
    public Integer getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.merchant_id
     *
     * @param merchantId the value for t_park_in_out_today.merchant_id
     *
     * @mbg.generated
     */
    public void setMerchantId(Integer merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.secTime_Payed
     *
     * @return the value of t_park_in_out_today.secTime_Payed
     *
     * @mbg.generated
     */
    public Double getSectimePayed() {
        return sectimePayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.secTime_Payed
     *
     * @param sectimePayed the value for t_park_in_out_today.secTime_Payed
     *
     * @mbg.generated
     */
    public void setSectimePayed(Double sectimePayed) {
        this.sectimePayed = sectimePayed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.secTime_Start
     *
     * @return the value of t_park_in_out_today.secTime_Start
     *
     * @mbg.generated
     */
    public String getSectimeStart() {
        return sectimeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.secTime_Start
     *
     * @param sectimeStart the value for t_park_in_out_today.secTime_Start
     *
     * @mbg.generated
     */
    public void setSectimeStart(String sectimeStart) {
        this.sectimeStart = sectimeStart == null ? null : sectimeStart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.ePayType
     *
     * @return the value of t_park_in_out_today.ePayType
     *
     * @mbg.generated
     */
    public Integer getEpaytype() {
        return epaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.ePayType
     *
     * @param epaytype the value for t_park_in_out_today.ePayType
     *
     * @mbg.generated
     */
    public void setEpaytype(Integer epaytype) {
        this.epaytype = epaytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.statistics_flog
     *
     * @return the value of t_park_in_out_today.statistics_flog
     *
     * @mbg.generated
     */
    public Integer getStatisticsFlog() {
        return statisticsFlog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.statistics_flog
     *
     * @param statisticsFlog the value for t_park_in_out_today.statistics_flog
     *
     * @mbg.generated
     */
    public void setStatisticsFlog(Integer statisticsFlog) {
        this.statisticsFlog = statisticsFlog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.inOut_status
     *
     * @return the value of t_park_in_out_today.inOut_status
     *
     * @mbg.generated
     */
    public Integer getInoutStatus() {
        return inoutStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.inOut_status
     *
     * @param inoutStatus the value for t_park_in_out_today.inOut_status
     *
     * @mbg.generated
     */
    public void setInoutStatus(Integer inoutStatus) {
        this.inoutStatus = inoutStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.coupon_type
     *
     * @return the value of t_park_in_out_today.coupon_type
     *
     * @mbg.generated
     */
    public Integer getCouponType() {
        return couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.coupon_type
     *
     * @param couponType the value for t_park_in_out_today.coupon_type
     *
     * @mbg.generated
     */
    public void setCouponType(Integer couponType) {
        this.couponType = couponType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_park_in_out_today.billing_status
     *
     * @return the value of t_park_in_out_today.billing_status
     *
     * @mbg.generated
     */
    public String getBillingStatus() {
        return billingStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_park_in_out_today.billing_status
     *
     * @param billingStatus the value for t_park_in_out_today.billing_status
     *
     * @mbg.generated
     */
    public void setBillingStatus(String billingStatus) {
        this.billingStatus = billingStatus == null ? null : billingStatus.trim();
    }
}