package com.common.entity.eparkingCloud;

public class TPropertyAutobill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property_autobill.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property_autobill.company_id
     *
     * @mbg.generated
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property_autobill.park_id
     *
     * @mbg.generated
     */
    private Integer parkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property_autobill.bill_item_id
     *
     * @mbg.generated
     */
    private Integer billItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property_autobill.bill_name
     *
     * @mbg.generated
     */
    private String billName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property_autobill.checkout_date
     *
     * @mbg.generated
     */
    private String checkoutDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property_autobill.autobill_push_date
     *
     * @mbg.generated
     */
    private String autobillPushDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property_autobill.amount
     *
     * @mbg.generated
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property_autobill.create_time
     *
     * @mbg.generated
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property_autobill.update_time
     *
     * @mbg.generated
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property_autobill.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_property_autobill.items_type
     *
     * @mbg.generated
     */
    private Integer itemsType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property_autobill.id
     *
     * @return the value of t_property_autobill.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property_autobill.id
     *
     * @param id the value for t_property_autobill.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property_autobill.company_id
     *
     * @return the value of t_property_autobill.company_id
     *
     * @mbg.generated
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property_autobill.company_id
     *
     * @param companyId the value for t_property_autobill.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property_autobill.park_id
     *
     * @return the value of t_property_autobill.park_id
     *
     * @mbg.generated
     */
    public Integer getParkId() {
        return parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property_autobill.park_id
     *
     * @param parkId the value for t_property_autobill.park_id
     *
     * @mbg.generated
     */
    public void setParkId(Integer parkId) {
        this.parkId = parkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property_autobill.bill_item_id
     *
     * @return the value of t_property_autobill.bill_item_id
     *
     * @mbg.generated
     */
    public Integer getBillItemId() {
        return billItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property_autobill.bill_item_id
     *
     * @param billItemId the value for t_property_autobill.bill_item_id
     *
     * @mbg.generated
     */
    public void setBillItemId(Integer billItemId) {
        this.billItemId = billItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property_autobill.bill_name
     *
     * @return the value of t_property_autobill.bill_name
     *
     * @mbg.generated
     */
    public String getBillName() {
        return billName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property_autobill.bill_name
     *
     * @param billName the value for t_property_autobill.bill_name
     *
     * @mbg.generated
     */
    public void setBillName(String billName) {
        this.billName = billName == null ? null : billName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property_autobill.checkout_date
     *
     * @return the value of t_property_autobill.checkout_date
     *
     * @mbg.generated
     */
    public String getCheckoutDate() {
        return checkoutDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property_autobill.checkout_date
     *
     * @param checkoutDate the value for t_property_autobill.checkout_date
     *
     * @mbg.generated
     */
    public void setCheckoutDate(String checkoutDate) {
        this.checkoutDate = checkoutDate == null ? null : checkoutDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property_autobill.autobill_push_date
     *
     * @return the value of t_property_autobill.autobill_push_date
     *
     * @mbg.generated
     */
    public String getAutobillPushDate() {
        return autobillPushDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property_autobill.autobill_push_date
     *
     * @param autobillPushDate the value for t_property_autobill.autobill_push_date
     *
     * @mbg.generated
     */
    public void setAutobillPushDate(String autobillPushDate) {
        this.autobillPushDate = autobillPushDate == null ? null : autobillPushDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property_autobill.amount
     *
     * @return the value of t_property_autobill.amount
     *
     * @mbg.generated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property_autobill.amount
     *
     * @param amount the value for t_property_autobill.amount
     *
     * @mbg.generated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property_autobill.create_time
     *
     * @return the value of t_property_autobill.create_time
     *
     * @mbg.generated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property_autobill.create_time
     *
     * @param createTime the value for t_property_autobill.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property_autobill.update_time
     *
     * @return the value of t_property_autobill.update_time
     *
     * @mbg.generated
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property_autobill.update_time
     *
     * @param updateTime the value for t_property_autobill.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property_autobill.user_id
     *
     * @return the value of t_property_autobill.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property_autobill.user_id
     *
     * @param userId the value for t_property_autobill.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_property_autobill.items_type
     *
     * @return the value of t_property_autobill.items_type
     *
     * @mbg.generated
     */
    public Integer getItemsType() {
        return itemsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_property_autobill.items_type
     *
     * @param itemsType the value for t_property_autobill.items_type
     *
     * @mbg.generated
     */
    public void setItemsType(Integer itemsType) {
        this.itemsType = itemsType;
    }
}